### ISSUE TITLE
Should there be a style guide, or guidelines in general?

### ISSUE THREAD

**Issue by darobin** [w3c/tr-design#1]
Does this need some form of style guide that people follow when adding to the styles? Can we just start organic?

**Comment by plehegar** [comment]
There should be a guide and we'll use the wiki of the repo for that to start.
I talked to Ian and he suggested two guidelines:
- the TR design must be accessible. I replied that i18n, security, privacy, etc. are also on the list and that's part of the "wide review" process I'm thinking
- the document must be readable even if Javascript is deactivated.

**Comment by fantasai** [comment]
Added to the README:

  <p>The following requirements apply to spec styling:

  <ul>
    <li>The document must be accessible to persons with disabilities. (See <a href="https://www.w3.org/WAI/standards-guidelines/wcag/">Web Content Accessibility Guidelines</a> for more info.)
    <li>The document must be readable even if JavaScript is disabled.
    <li>The document must be readable when printed.
    <li>The document must be readable across all browsers, platforms, and operating systems with current widespread usage anywhere in the world, on both desktop and mobile devices. (Note this requirement is more stringent than working across the “latest version” of all browsers/platforms/operating systems.)
  </ul>

Marking this closed; file separate issues if you want additional things tweaked.
