### ISSUE TITLE
I can fit my whole head into the wasted space...

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/tr-design#102]
Check it out, my whole head fits into the amount of wasted space:

![screenshot 2016-07-20 18 57 23](https://cloud.githubusercontent.com/assets/870154/16980980/e2b2a29a-4eab-11e6-8445-6b90d3615596.png)

If we are going to stick to a set width, then `margin: auto` the document for large screen?

**Comment by liamquin** [comment]
On Wed, 2016-07-20 at 01:59 -0700, Marcos Cáceres wrote:

> Check it out, my whole head fits into the amount of wasted space:

If browsers were better at them, using multiple columns on large
screens might be an improvement. As it is, the space is not wasted, as
it leaves room for your head :-) Arbitrarily long lines of text aren't
an improvement for reading, though, since people tend to get tired
sooner and make mistakes when reading especially long lines.

**Comment by marcoscaceres** [comment]
I'm not a fan, nor have I seen any science behind the long-line claim. I read with a screen reader (text to speech, so line length is not an issue for me because I use two modalities for input: sound and vision). My point is that specs should be center aligned, not left aligned. The left alignment is silly and unhelpful because I need to resize my browser and move the window over every time I open a w3c spec.

**Comment by fantasai** [comment]
I had centered it in the past, and then ppl complained. :P Can't make everyone happy... I can set up a poll if you feel strongly about it? Left-alignment works better for oversized images and tables, fwiw. Also, if you collapse the sidebar it'll center.

Multi-col would be great, but won't be usable until we have fragmented overflow controls. :/ Currently only usable in print, which paginates.

In the meantime, Marcos, how about you get yourself a better window manager to take advantage of that wasted space? :D

**Comment by marcoscaceres** [comment]
> I had centered it in the past, and then ppl complained. :P 

People are the worst! 

> In the meantime, Marcos, how about you get yourself a better window manager to take advantage of that wasted space? :D

Heh, I have thought of moving to Windows 10 for fun. 

The problem is not so much window management, it's that swapping from one tab to another: where one web applications works well (Github being the perfect example) because of centering, w3c specs don't.

**Comment by marcoscaceres** [comment]
> Also, if you collapse the sidebar it'll center.

I was not aware of that fallback - will use that.
