### ISSUE TITLE
data tables align center

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/tr-design#104]
The data table in the example seems to center align to the window, which kinda throws off the column-width restricted design:

![screenshot 2016-08-05 16 59 28](https://cloud.githubusercontent.com/assets/870154/17428755/234bd270-5b2e-11e6-8f5f-df1ce6a85ea6.png)

**Comment by marcoscaceres** [comment]
Also, those tables should have an border around the outside... in the manifest spec, I would get double sadness as it would look like this: 

![screenshot 2016-08-05 17 02 41](https://cloud.githubusercontent.com/assets/870154/17428824/9363006a-5b2e-11e6-920c-e6e5b8c3f626.png)

**Comment by domenic** [comment]
Ping @fantasai; this continues to be a really big problem on multiple specs using W3C stylesheets. Examples from Web IDL:

- https://heycam.github.io/webidl/#idl-members
- https://heycam.github.io/webidl/#idl-special-operations
- https://heycam.github.io/webidl/#dfn-distinguishable

I tried to left-align these using inline styles (`margin: 0 !important` for the `.overlarge` class), but something in the Bikeshed output is overriding it with another `!important` declaration later than I can place my own `!important` declarations :(. /cc @tabatkins

**Comment by tabatkins** [comment]
Okay, I've done some fiddling, and as far as I can tell I've fixed the problem.

First, re-iterating our design constraints:

1. We have a "text column width", which is generally 50em wide, or smaller if the viewport is too small.
2. We have an "available width", which is the text column width, plus any open space to its right. This only shows up on wide monitors.

Now, the functionality we want is:

1. When the table's width is less than the text column width, the table should be centered in the text column.
2. When the table's width is greater than the text column width, but less than the available width, left-align the table in the available width (filling the text column and spilling out rightwards).
3. When the table's width is greater than the available width, fill the available width, and pop a local scrollbar to allow viewing the rest of the table.

We already have a `<div class=overlarge>` wrapping every table, which uses clever margin trickery to be the size of the "available width". The table is then nested directly into there. Using this, our current CSS instead *always* centers the table into the "available width", which looks bad on wide screens. (But it does correctly generate a scrollbar when the table is too wide, which is the primary goal.)

It looks like it's quite easy to fix this to satisfy all our desired behaviors, by just adding the following:

```css
div.overlarge {
 display:grid;
 grid-template-columns: minmax(0, 50em);
}
```

@fantasai, could you verify that this fixes table layout? It appears to in all my tests.

(Alternately, if we don't want to rely on Grid, we could add a second wrapper div, giving it a `max-width:50em;`. I'm pretty sure this will achieve the same thing.)

**Comment by tabatkins** [comment]
I've just fixed this in Bikeshed's default stylesheet, and confirmed it works exactly as I want it to, so I've opened a PR (#185) to fix it in the W3C stylesheets as well.

**Comment by fantasai** [comment]
Merged PR https://github.com/w3c/tr-design/pull/185

**Comment by tabatkins** [comment]
Now that #185 is merged, this can presumably be closed? Are you waiting for confirmation from @marcoscaceres, perhaps?

**Comment by domenic** [comment]
Confirmed that the linked Web IDL examples are fixed!

**Comment by marcoscaceres** [comment]
Confirmed also (web manifest spec)! Closing as fixed.
