### ISSUE TITLE
`dl dt code, code.idl` should be `font-size: normal`, not `inherit`

### ISSUE THREAD

**Issue by tabatkins** [w3c/tr-design#105]
Found in https://github.com/w3c/tr-design/blob/gh-pages/src/base.css#L456.

**Comment by fantasai** [comment]
`font-size: normal` isn't valid CSS. What did you mean here?

**Comment by plehegar** [comment]
closing due to lack of response. feel free to reopen if new information.

**Comment by tabatkins** [comment]
I clearly meant `medium`, the initial value.

**Comment by tabatkins** [comment]
The point of it is that if you have nested `<code>`, and you have, say, "font-size: 90%" on it, then a `<code class=idl>` will inherit that % and end up with an effective 81% font-size.  (This was an actual problem I encountered.)

And I don't have rights to re-open.

**Comment by plehegar** [comment]
See #119

**Comment by plehegar** [comment]
Computed value of `font-size` is always an absolute length, see https://www.w3.org/TR/CSS21/fonts.html#font-size-props If your implementation is multiplying the percentage as it inherits, then it's broken. File a bug against your engine.

-- fantasai
