### ISSUE TITLE
Should the use of !important be forbidden

### ISSUE THREAD

**Issue by astorije** [w3c/tr-design#11]
Since the pubrules checker checks that the W3C stylesheets are mentioned last in the list of stylesheets of a document, a lot of documents are making use of `!important`...

Should this be prevented by policy? I mean, there won't be any good reason to use it once the TR design is always cool and modern...

Regarding enforcing this rule, I know people will say that we simply cannot because it's easy to manipulate CSS with JS, but I would argue that this is true for pretty much everything in a document so at this point we ask people to be reasonable. Without going that far, it means Specberus would need to check inline CSS (`<style>` tag and `style` attributes) as well as external CSS files.

**Comment by darobin** [comment]
I don't think that this should be enforced. If someone breaks some essential part of the styling because of that, well, we can solve the problem socially.

**Comment by plehegar** [comment]
One go around this limitation by adding additional classes or an ID on the element. So preventing the use of !important would not prevent anything imho.

**Comment by jspellman** [comment]
I agree with darobin.  Please don't add more complications to pubrules.  Our goal is to make it easier to publish, not harder.  This can be better handled socially.

**Comment by astorije** [comment]
I would not indeed, but I warned you in the description anyway :-)
The point is not to set only up rules that we can enforce with 100% precision, but that we can reasonably enforce. Because, let's face it, **none** of our rules can be completely enforced (as the webmaster, I know how to trick a webmaster to publish a Trololo video that pleases him and the checker :P).

That was just a suggestion, if forbidding `!important` by policy is not relevant, please close with `wontfix` label :-)

**Comment by fantasai** [comment]
I don't think we need to enforce this, however if someone is using !important in their styles, that's a good indication that the W3C styles have a problem.
