### ISSUE TITLE
Add "ednote" class

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/tr-design#110]
ReSpec has an "Editor's Note" type note that is [used quite a lot](https://github.com/search?l=HTML&q=org%3Aw3c+ednote&type=Code).

It's exactly the same as a note in rendering, but I would like to drop it from ReSpec and have it become part of base.

**Comment by fantasai** [comment]
What's the difference between an “Editor’s Note” and a “Note” if they are rendered the same?

**Comment by marcoscaceres** [comment]
No difference, though we could change that if we want - would not be a bad thing. However, if I remove that CSS from ReSpec, it will break existing specs that are relying on it.

**Comment by fantasai** [comment]
If there is no difference -- if they are merely synonyms, then I don't see the point in adding anything to base.css. As for compatibility with existing specs... ReSpec is a spec output generator, right? Why couldn't it simply convert ednote to note for output?

**Comment by marcoscaceres** [comment]
I was hoping base.css would alias it, then I don't need to convert it in ReSpec (or we could actually differentiate them from notes). However, I can do what you suggest in ReSpec and start warning people to just use a "note".

**Comment by marcoscaceres** [comment]
(I'll take it that you are not interested in differentiating them either  - which is totally ok - but need a concrete answer so I know what to do)

**Comment by fantasai** [comment]
If there's no benefit to anyone else to adding ednote, then I think ReSpec handling is best. I don't want to put anything in base.css that isn't useful to nearly everyone.

**Comment by marcoscaceres** [comment]
Ok, but maybe take a look at the specs that are using the ednotes already (there were quite a few) - I've personally never felt the need to use them, but I don't know about other spec editors and if they find them of value.

**Comment by marcoscaceres** [comment]
I'm looking at the specs that use them and my gut tells me we should maybe ask on spec-prod if editors would like to see them differentiated? People seem to like having them - but because they look the same as notes, it makes them hard to spot.

**Comment by fantasai** [comment]
Yeah, sure. Wanna start a thread, or should I?

**Comment by fantasai** [comment]
Fwiw, CSSWG tends to use either "note" or "issue", depending on whether we're explaining something or describing a problem that needs resolving. We haven't found a reason to have an "editor's note" that's distinct from either of these concepts.

**Comment by marcoscaceres** [comment]
I emailed spec-prod - cc'ed you. I suspect that I'll be changing ReSpec tho - but let's leave this open for a week or so.

**Comment by plehegar** [comment]
The thread is at
 https://lists.w3.org/Archives/Public/spec-prod/2017JanMar/0015.html

Last email from @tabatkins indicates: "All of this is supporting the argument that "ednote" doesn't have a strong semantic concept, making it unclear precisely when to use it.". So I conclude the answer was no at the end and closing this issue. Feel free to reopen if you feel otherwise.

**Comment by marcoscaceres** [comment]
thanks for the discussion, I'll make the appropriate changes to respec https://github.com/w3c/respec/issues/1239
