### ISSUE TITLE
race for a11y position

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/tr-design#113]
The fixup.js script is currently doing this: 

```JS
      /* Prepend for better keyboard navigation */
      document.body.insertBefore(tocNav, document.body.firstChild);
```

But that causes problems with things like the ReSpec pill wanting to be the first thing in the DOM tree for a11y reasons. 

@fantasai, do you have any recommendations?

**Comment by fantasai** [comment]
um, question: why does the ReSpec pill want to be the first thing in the DOM, even before the link to the ToC?

**Comment by marcoscaceres** [comment]
Ah, sorry, I was confused. The order is correct.
