### ISSUE TITLE
Snapshot status

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/tr-design#114]
See: 
https://s3.amazonaws.com/pr-preview/rmisev/url/empty-host-for-file.html

Would be great to this be a general thing for BS and ReSpec.

**Comment by marcoscaceres** [comment]
(note, the current thing is a bit of overkill... but something the minimal red bar down the bottom of the window is nice).

**Comment by fantasai** [comment]
We currently have .annoying-warning for these: http://fantasai.inkedblade.net/style/design/w3c-restyle/2016/sample#obsolete Happy to improve the styling, but I think that should suffice for the purpose, no?

**Comment by marcoscaceres** [comment]
Using `.annoying-warning` should work - but it would be great to have it stick to the bottom of the doc if possible.

**Comment by fantasai** [comment]
You mean like this: https://github.com/w3c/tr-design/blob/gh-pages/src/base.css#L707 ???

**Comment by marcoscaceres** [comment]
Ah, nice! Could we get that documented here: https://w3c.github.io/tr-design/src/sample.html#obsolete

**Comment by fantasai** [comment]
Um. It is documented. I didn't put an example in because it would be hella annoying. :) I can tweak the wording on the documentation; what specifically would you like adjusted?

**Comment by marcoscaceres** [comment]
>  I didn't put an example in because it would be hella annoying

Sorry, I meant just a code example - not a live one. 

> what specifically would you like adjusted?

Somethings like:

> The .annoying-warning is for spec obsoletion notices. They're a bit scary, and should only occur once per spec. It can be used with a block level element or, if you want the notice to appear at the bottom of the document, use it on an `details` element.   

>For example: 

```HTML
<details class="annoying-warning">
  <h?>This spec is obsolete</h?> 
  <p>This specification is obsolete. See x, y, z  for details.</p>
</details>
```

> It renders something like this:
> [[ SCREEN SHOT  ]] 

In particular, guidance on the heading would be great, etc. Something that people can just copy/paste/adjust.

**Comment by marcoscaceres** [comment]
Fixed s/aside/details above.

**Comment by tobie** [comment]
once it's shipped, If you can let me know how to account for this in pr-preview, that would be nice. :)

**Comment by plehegar** [comment]
@tobie not sure what you mean by "shipped". That part of the stylesheet is into https://www.w3.org/StyleSheets/TR/2016/base.css . Am I missing something? If not, then it got shipped a while ago...

**Comment by tobie** [comment]
Sorry, yes.

The title of this issue is "Snapshot status." What I was hoping for was a dedicated style that could be invoked from both Bikeshed and ReSpec by passing in a dedicated status like we have ED, WD, CR, REC, etc. along with a related PR number, link to the PR, etc. The end goal is to have a document that fulfills it's previewing / snapshotting purpose and is recognizable as such, in style, SOTD content and warning.

/cc @tabatkins

**Comment by tabatkins** [comment]
Bikeshed currently has `LS-COMMIT` and `LS-BRANCH` which, along with `Warning: commit [snapshot id] [snapshot url] replaced by [master url]` or `Warning: branch [branch name] [branch url] replaced by [master url]`, can easily denote something as a commit/branch and thus not the mainline spec.

**Comment by tobie** [comment]
Right. Which is what WHATWG uses. It requires a hefty config file. I was hoping for something more lightweight. And  possibly more specific to W3C.

**Comment by tabatkins** [comment]
> It requires a hefty config file.

??? What do you mean by that?  It's literally a single `Warning` metadata.

**Comment by tobie** [comment]
Sorry, I meant the pr-preview config file is hefty.

I'd like to see at most this:

```json
{
    "src_file": "fetch.bs",
    "type": "bikeshed",
    "params": {
        "md-status": "GH-PR",
        "md-pr-url": "{{ pull_request.html_url }}",
        "md-pr-number": "{{ pull_request.number }}"
    }
}
```

Not this (here for the [pr-preview config file](https://github.com/whatwg/fetch/blob/master/.pr-preview.json) of the fetch API):

```json
{
    "src_file": "fetch.bs",
    "type": "bikeshed",
    "params": {
        "force": 1,
        "md-status": "LS-COMMIT",
        "md-h1": "URL <small>(<a href=\"{{ pull_request.html_url }}\">PR #{{ pull_request.number }}</a>)</small>",
        "md-warning": "Commit {{ short_sha }} {{ pull_request.head.repo.html_url }}/commit/{{ sha }} replaced by {{ config.ls_url }}",
        "md-title": "{{ config.title }} (Pull Request Snapshot #{{ pull_request.number }})",
        "md-Text-Macro": "SNAPSHOT-LINK {{ config.back_to_ls_link }}"
    },
    "ls_url": "https://fetch.spec.whatwg.org/",
    "title": "Fetch Standard",
    "back_to_ls_link": "<a href=\"https://fetch.spec.whatwg.org/\" id=\"commit-snapshot-link\">Go to the living standard</a>"
}
```

**Comment by tabatkins** [comment]
Where's the pr-preview tool? It clearly runs off and grabs some more information - I presume that's just from the GH API?

**Comment by tobie** [comment]
Oh, it this: https://github.com/tobie/pr-preview

I didn't know you weren't familiar with it. Sorry.

You can see it in action here for example: https://github.com/w3c/sensors/pull/179

**Comment by tabatkins** [comment]
Cool. (I was familiar with the existence of the tool, just not how it actually worked.)

This seems pretty reasonable to put together with some auto-magic.

**Comment by tobie** [comment]
Basically, the ideal scenario from my perspective is this to be somehow built-in to Bikeshed and ReSpec. That let's us avoid huge pr-preview config files that need to be updated in all repos when there's a change. It also avoids having spec styling spread out across multiple projects.

**Comment by tabatkins** [comment]
Yeah, I agree with this goal.

**Comment by plehegar** [comment]
fyi, on this front, our current goal is to automatically supersede old drafts when a new one gets published. @deniak  tested a few approaches and narrowed down it. It shouldn't require any change to the stylesheets but would require additional JS however. We're packaging the proposal along the TR versioning one and the revamping of the /TR pages btw. Expect more to come asap on spec-prod for this front.

**Comment by tobie** [comment]
@plehegar well, the goal of these pull request preview documents is certainly not to have them redirect to the main document. They're useful to assess the impact of a change. What you want is just clarity that it's what they're doing.

**Comment by plehegar** [comment]
We shipped the automatic deprecation mechanisms last year. Bikeshed seems to have been updated. Is there anything to do for this issue?

**Comment by tobie** [comment]
Both Bikeshed (https://github.com/tabatkins/bikeshed/issues/1031) and ReSpec (https://github.com/w3c/respec/issues/1339) have open issues, so as far as I'm concerned, you may close.

**Comment by fantasai** [comment]
Added example as requested; no heading, just `<summary>`. ;)
