### ISSUE TITLE
It should be possible to produce EPUB format from our TR documents

### ISSUE THREAD

**Issue by iherman** [w3c/tr-design#12]
I think that, at long term, we should be able to routinely produce EPUB formats for our documents as an offline/download format (to replace the PDF versions that many TR documents offer). 

This should not affect CSS styling; EPUB can handle those without problems. However, if (local) Javascript is used for the documents, we should check whether they are acceptable for EPUB (on long term, that should not be a problem either, but there may be limitation on short term.

Where it may require extra consideration is when a TR document consists of several files (typical for large specs like HTML5 or SVG). In that case a separate navigation file (table of content) should be made available, because it is not necessarily obvious how to generate those automatically from, say, respec sources. In general, the documents should be such that it should be easy to generate such EPUB via, say, a respec module; this may affect the structure of the document (adding some info to links to make the targets local for an EPUB file, etc.)

**Comment by jspellman** [comment]
+1.  Companies (including member organizations) are moving away from PDF to EPUB.  We need to support it now so we aren't playing catchup a year or two from now.

**Comment by fantasai** [comment]
This is out of scope. Please file this issue against the relevant spec preprocessors. W3C does not restrict the number of alternate formats that a WG chooses to serve.
