### ISSUE TITLE
Lightly right-pad var?

### ISSUE THREAD

**Issue by tobie** [w3c/tr-design#123]
Variables (denoted by `<var>foo</var>`) are represented in italics. A common construct we no have is:

```html
<var>list</var>[<var>i</var>]
```

which renders as: <var>list</var>[<var>i</var>] and is overly crammed.

I've played with a subtle CSS and:

```css
var { padding-right: 0.1em }
```

seems to be an improvement.

Is there any reason it's a bad idea, and if not, can it (or a variation of it) make its way into the main stylesheet?

**Comment by fantasai** [comment]
Hi @tobie, I understand exactly the situation you're describing, I've seen it before. However, on my system I'm not seeing the problem. Which I think means, whether the extra padding is appropriate or not depends on the metrics of the font in use. I'm guessing some fonts measure the "advance" of the glyph along the baseline, whereas others (newer ones, maybe?) measure the glyph in a way that lets it sit with non-italic text a little better.

Given that dependency on font metrics, I'm leaning towards not compensating in the style sheet.

**Comment by tobie** [comment]
Makes sense.
