### ISSUE TITLE
About various note style sheets

### ISSUE THREAD

**Issue by xfq** [w3c/tr-design#124]
There are three types of notes:

* https://github.com/w3c/tr-design/blob/gh-pages/src/W3C-IG-NOTE.css
* https://github.com/w3c/tr-design/blob/gh-pages/src/W3C-WG-NOTE.css
* https://github.com/w3c/tr-design/blob/gh-pages/src/W3C-NOTE.css

The first two are pretty easy to understand... What does the third one stand for?

/cc @deniak

**Comment by deniak** [comment]
@ianbjacobs will know more about that one but if I'm not mistaking, `W3C-NOTE.css` is the first CSS used for Notes but is no longer used. The [process document 2003](https://www.w3.org/2003/06/Process-20030618/) introduced the concept of WG Notes and IG Notes which are still valid these days.

**Comment by ianbjacobs** [comment]
I think @deniak is correct.

Here's an example of an old spec using W3C-NOTE:
 https://www.w3.org/TR/1999/NOTE-TVWeb-URI-Requirements-19991021

Ian
