### ISSUE TITLE
Chrome android 62 and outdated note

### ISSUE THREAD

**Issue by plehegar** [w3c/tr-design#128]
The outdated red note appears off the screen when opening an out-of-date TR document with Chrome android 62. Works fine with Firefox 57 on android.

**Comment by deniak** [comment]
I can't reproduce the bug. I tried with chrome beta (62) and chrome 61 on android and the note appears in the middle of the screen.
Can you take a screenshot and tell me the phone/tablet you are using?

**Comment by plehegar** [comment]
Tried on GalaxyS8/Chrome62 and GalaxyS6/Chrome61 and got the same result. :(
Sent the screenshots to webreq.

**Comment by deniak** [comment]
Do you have the same problem with that spec: https://www.w3.org/TR/2017/WD-appmanifest-20170920/ ?

**Comment by plehegar** [comment]
nope. That one works fine.

**Comment by deniak** [comment]
I narrowed the issue a little bit.
The problem comes from the 2 `<table>`s in the document. They are larger than the `body` which is causing a problem with the margin computation of the warning in Chrome.

**Comment by deniak** [comment]
@plehegar I can't reproduce the bug anymore with the latest update of chrome 62. Can you try again and let me know if you still have the bug?

**Comment by plehegar** [comment]
Still have the bug with the 26 September version of https://www.w3.org/TR/html-aria/
using Chrome 63.

**Comment by plehegar** [comment]
JUst checked with https://www.w3.org/TR/hr-time previous version and it works fine. html-aria previous version is still broken but not worth instigating at this point imho.
