### ISSUE TITLE
More white space please

### ISSUE THREAD

**Issue by r12a** [w3c/tr-design#13]
I'd like (much) more white space before h2 and h3, so that it's easier to spot where sections start and end, and read the titles. (Extra space not necessarily needed in the SOD area.)

**Comment by plehegar** [comment]
Got a proposal for the existing style sheets? "more spacing" is a bit vague... How much px/em/etc. (pick your favorite unit) would you like?

**Comment by r12a** [comment]
here's an example of what we do for i18n WDs.  Note how the extra space is not used for headings in the SOTD section.
http://www.w3.org/TR/klreq/

**Comment by fantasai** [comment]
Hi r12a, I merged in the CSSWG styles. Please reopen if this has not yet been fixed to your satisfaction.
