### ISSUE TITLE
Small-screen/zoom issues in styling

### ISSUE THREAD

**Issue by alastc** [w3c/tr-design#134]
Hi,

One of the new WCAG 2.1 success criteria is about '[Reflow](https://w3c.github.io/wcag21/guidelines/#reflow)', allowing users to zoom into to a high degree (400% from a starting point of 1280px wide) without loosing content/functionality.

The specs in general reflow well, but there is one noticable (if relatively minor) issue in the draft spec:
<img src="https://alastairc.ac/tmp/spec-screenshot.png" alt="screenshot of spec zoomed in">

The Editor's draft background image gets hidden behind the TOC arrows.

I don't think there are any (good) options for resizing the background image based on screen height, but perhaps it could use a vertical media query to specify it should only appear when there is 320px (or more) of vertical height?

NB: The 'respec' box is a little annoying but I assume won't be on the public published version. The arrows just about fit, I don't think they cause an issue.

**Comment by tripu** [comment]
Thanks for reporting, @alastc.

I also think it's a minor issue; the text &ldquo;W3C Editor's Draft&rdquo; is shown (as text) at the top of documents. The background image isn't conveying vital information; it's there to provide different &ldquo;identities&rdquo; to different types of specs, at a quick glance (I think).

The Respec *pill* won't be there on specs published on [`https://www.w3.org/TR/`](https://www.w3.org/TR/), no.

**Comment by alastc** [comment]
Yep, I just note it beause there is some sensitivity about meeting our own specs, so good to adjust if possible :-)

**Comment by tripu** [comment]
I think we can close this issue. That is a background image (not text), the information it conveys is redundant anyway, and it's okay if it's partly obscured by content.

**Comment by alastc** [comment]
Ok, I saw elsewhere that the specs might be re-designed anyway, so happy to drop this.
