### ISSUE TITLE
<details class="note"> styling removes disclosure triangle in browsers that support styling the disclosure triangle

### ISSUE THREAD

**Issue by dbaron** [w3c/tr-design#148]
This is a report of a bug in [the 2016 base TR stylesheet](https://www.w3.org/StyleSheets/TR/2016/base.css).

I noticed this while reading [the Typed OM section on CSSTransformValue](https://drafts.css-houdini.org/css-typed-om-1/#transformvalue-objects).

After the IDL block, there's a &lt;details class="note"> whose summary is "is2D Design Considerations".  The disclosure triangle for this &lt;details> is missing in Firefox, but present in Chrome.  It's missing in Firefox because Firefox implements styling of &lt;details> [as specified](https://html.spec.whatwg.org/multipage/rendering.html#the-details-and-summary-elements) where the disclosure triangle is a list marker, and appears because the &lt;summary> is display:list-item.  Changing the display of summary from list-item to block causes the disclosure triangle to disappear, because Firefox supports the spec's mechanism for styling the disclosure triangle.

The base [stylesheet](https://www.w3.org/StyleSheets/TR/2016/base.css) contains (with line numbers):

    674         .note::before, .note > .marker,
    675         details.note > summary::before,
    676         details.note > summary > .marker {
    677                 text-transform: uppercase;
    678                 display: block;
    679                 color: hsl(120, 70%, 30%);
    680         }
    681         /* Add .note::before { content: "Note "; } for autogen label,
    682            or use class="marker" to mark up the label in source. */
    683
    684         details.note > summary {
    685                 display: block;
    686                 color: hsl(120, 70%, 30%);
    687         }

I believe the correct fix for this is to remove line 685 from the style sheet.  Note that line 678 should remain; it is not styling summary elements.

I'd like to see the fix for this backported into the existing style sheet given that it's causing browser differences in the appearance of W3C specifications.

**Comment by fantasai** [comment]
Fix committed. @tripu Can you deploy this?

**Comment by tripu** [comment]
(It was deployed; see CSS rule in line no. 686 of [`https://www.w3.org/StyleSheets/TR/2016/base.css`](https://www.w3.org/StyleSheets/TR/2016/base.css))
