### ISSUE TITLE
TOC text collapsed in Safari 11.0.3

### ISSUE THREAD

**Issue by ZoeBijl** [w3c/tr-design#149]
Fairly sure this is also the case in Safari 10 but don’t have that on hand.

<img width="393" alt="Text from TOC overlaps itself causing it to become illegible" src="https://user-images.githubusercontent.com/5457769/36850896-28aff806-1d68-11e8-94fc-6fd762f60c5a.png">

**Comment by fantasai** [comment]
It's a bug in Safari's handling of 'rem' units, IIRC. The Safari team fixed it...

**Comment by ZoeBijl** [comment]
Tried to search for the bug in Bugzilla but couldn’t find it. Anyhoo, I can’t reproduce this on any of the current specs in Safari 11.1. So it seems they did indeed fix it.
