### ISSUE TITLE
Make it easier to point to github/bugzilla for comments please

### ISSUE THREAD

**Issue by r12a** [w3c/tr-design#15]
I like to see a way to point people to github/bugzilla as the preferred location for comments on the document that blends with the information on mailing lists.

**Comment by svgeesus** [comment]
Some groups are already doing that, adding a link to the issues list in the top matter. If that link is to a dynamic site like github issues, it is also the way to report them. In the case of a static document though, it isn't. Maybe those need to be two separate things.

**Comment by r12a** [comment]
Respec spits out a formulaic paragraph about where to send comments that takes in information only about mailing lists, afaia.  I think it needs to produce something recognisable for pubrules checker. I checked with Robin, and ended up having to add a brightly highlighted note to the SoTD in order to get the message across. See http://www.w3.org/TR/klreq/  It's awkward to say the least.

**Comment by plehegar** [comment]
@r12a, Some groups are using repository and mailing list information in the headers. See http://www.w3.org/TR/appmanifest/ for an example.

**Comment by r12a** [comment]
For an example of what i18n currently does in this respect, see the SOTD in http://www.w3.org/TR/klreq/

**Comment by fantasai** [comment]
This is out of scope for the style sheets, but will hopefully be tackled in a boilerplate redesign after this year.

**Comment by r12a** [comment]
how do we ensure that this is reraised at the appropriate time?

**Comment by fantasai** [comment]
It's already tracked at http://www.w3.org/wiki/SpecProd/Restyle/Content

**Comment by r12a** [comment]
great
