### ISSUE TITLE
Harmonising variable highlight colors in ReSpec and Bikeshed

### ISSUE THREAD

**Issue by sidvishnoi** [w3c/tr-design#152]
[Recently](https://lists.w3.org/Archives/Public/spec-prod/2018AprJun/0008.html), ReSpec released a feature that will allow spec readers to click on variables in an algorithm and highlight where they are used (see [feat:highlightVars](https://github.com/w3c/respec/wiki/highlightVars)). Bikeshed announced the same (https://github.com/tabatkins/bikeshed/issues/1236). 
It would be great if we could come to an agreement between Bikeshed's selection of color palette and that of ReSpec, keeping accessibility in mind.

Here are the present colors:
<img width="300" src ="https://user-images.githubusercontent.com/8426945/39535049-927c6df0-4e50-11e8-8270-41f6894330f1.png">

I've also added a [preview gif](https://github.com/w3c/respec/wiki/highlightVars) for ReSpec's highlightVars in action. We used colors inspired by GitHub labels.

ReSpec renders like this:
![screenshot 2018-05-03 14 57 16](https://user-images.githubusercontent.com/870154/39560580-90fa140e-4ee2-11e8-9a48-c34da468b48e.png)

Would people prefer BikeShed's colors? ReSpec's colors? Or something else?

**Comment by marcoscaceres** [comment]
BikeShed spec sample: https://heycam.github.io/webidl/

**Comment by duerst** [comment]
In general, I prefer the Bikeshed colors, because they are less obtrusive.

**Comment by tabatkins** [comment]
I think my color set needs some tweaking to make the colors a little more distinct from each other.

But yeah, I started from a pastel yellow like the ES spec uses.  (And when we decide on colors, ES will match us.)

**Comment by sidvishnoi** [comment]
Personal opinion: I find ReSpec's colors to be too vibrant and the ones in Bikeshed too light. Hopefully we can come up with something intermediate.

**Comment by marcoscaceres** [comment]
The ReSpec colors are a mix of a custom high contrast palette and somewhat inspired by github's label colors. This was the original source of inspiration: 

![screenshot 2018-05-08 16 29 55](https://user-images.githubusercontent.com/870154/39741378-102bb360-52dd-11e8-8d56-a5acfa8a470b.png)
 
The problem we found with using GitHub's colors were that they require a bit of padding to make contrasting work well, but then we didn't want to reflow the document (adding padding made everything "flash" on click, and it too jarring). 

Using BikeShed's colors, we've put together a little pen: 
https://codepen.io/anon/pen/wjpMYK

![screenshot 2018-05-08 17 59 48](https://user-images.githubusercontent.com/870154/39745090-a0b35f9e-52e9-11e8-8af3-2f12f9b491eb.png)

I think something in the l=70% looks quite good in terms of contrast (at least on my monitor). 

Can others take a look? Feel free to fork the above and make modifications.

**Comment by duerst** [comment]
My personal preference would be closer to 90% or 80% rather than 70%, in particular for red and purple. Also please note that in particular red and purple look darker than the other colors, an effect that gets stronger for lower percentages, so a correction may be needed.

**Comment by tabatkins** [comment]
Yeah, most of them in the 80% range look great to me. I'd just tweak the red/purple a little lighter, as @duerst says.  70% is already running into some serious contrast issues.

(Probably I'll convert them to Lab and make sure they have the same brightness, rather than trying to eyeball them.)

**Comment by marcoscaceres** [comment]
Definitely can work with 80% (slightly light for my eyes/monitor, but definitely usable). 

@sidvishnoi, after your exams this week, would you mind making the adjustments above and posting the values and screenshot here? We can then integrate them into ReSpec and BikeShed.

**Comment by sidvishnoi** [comment]
> @sidvishnoi, after your exams this week,...

surely. will do so!

**Comment by tabatkins** [comment]
Yeah, as noted, the red and purple are significantly darker than the others. Here's the six colors from the codepen in Lab:

* yellow hsl(60, 50%, 80%) = 90.35 -6.00 24.99
* red hsl(0deg, 50%, 80%) = 77.67 19.08 7.50
* green hsl(120deg, 50%, 80%) = 86.75 -24.28 19.38
* teal hsl(180deg, 50%, 80%) = 87.75 -16.93 -5.65
* orange hsl(30deg, 50%, 80%) = 83.77 6.58 16.02
* blue hsl(240deg, 50%, 80%) = 74.28 8.06 -25.69

I think we can roll with a uniform 85 lightness, it's an easy target to hit for the colors. That'll give us...

* yellow = #D7D7A4
* red = #FBC7C7
* green = #AFE1AF
* teal = #ABDEDF
* orange = #EACFB6
* blue = #D0D1FF

I [forked the CodePen](https://codepen.io/TabAtkins/pen/aGqarE) with the new colors. They need some tweaking for shade, but I'm very happy about the consistent brightness. (Working in a perceptual colorspace helps, who knew?)

**Comment by tabatkins** [comment]
[Here's another CodePen](https://codepen.io/TabAtkins/pen/RyQYzv) with the shades from above, and tweaked version that pull them further apart and look a little better. All are still 85 lightness.

**Comment by marcoscaceres** [comment]
Tweaked version look great! Nice and legible, and contrasts well. I'd support going with those. 

@duerst, @sidvishnoi, wdyt?

**Comment by duerst** [comment]
@marcoscaceres: Agree, looks good!

**Comment by sidvishnoi** [comment]
Thank you everyone! :slightly_smiling_face:
