### ISSUE TITLE
Repo "Website" is a broken link

### ISSUE THREAD

**Issue by jyasskin** [w3c/tr-design#157]
The "website" field that appears at https://github.com/w3c/tr-design under "Insights" and to the right of "Style Sheets used by W3C Technical Reports http://www.w3.org/TR/" is https://w3c.github.io/tr-design/src/sample.html but should be https://w3c.github.io/tr-design/src/readme.html.

**Comment by vivienlacourba** [comment]
fixed (not sure when).
