### ISSUE TITLE
Making it crystal clear when content is Normative 

### ISSUE THREAD

**Issue by goodwitch** [w3c/tr-design#172]
While it is "easy" for active W3C participants to understand what parts of publications are normative (and what parts are informative)...this is NOT clear to regular humans that have to use these standards.  In the case of WCAG 2.0 and 2.1, I've talked to hundreds of accessibility professionals that think 'Understanding" and "Technique" documents are normative.  

Please, please add a clear text and visual indicator when content is Normative and a different clear text and visual indicator when content is Informative.  

I cannot tell you how many times I've used this small sentence in WCAG 2.0 to explain this concept to people.  "This section is normative." (see it at https://www.w3.org/TR/WCAG20/#guidelines )  

And I was shocked to see that this VERY VERY IMPORTANT sentence is no where to be found in the recently published WCAG 2.1 rec.   Do y'all really think people go down to section 5.1 to read this sentence "The main content of WCAG 2.1 is normative..."?

**Comment by fantasai** [comment]
Hi! /tr-design is about the visual design of the documents across all of W3C. We don't control the actual text content of the specs, you'd have to take that up with the authors of the document.

**Comment by goodwitch** [comment]
@michael-n-cooper can you help us figure out where to report this?  Looks like tr-design isn't the right place.

**Comment by marcoscaceres** [comment]
@goodwitch, looks like the right place might be https://github.com/w3c/WCAG

**Comment by goodwitch** [comment]
@marcoscaceres it actually needs to be higher than that.  Michael was telling me that it is a W3C TR/spec construct...so asking down at the WCAG level is too low.

**Comment by marcoscaceres** [comment]
I guess it could be done at the ReSpec (spec generator) level. It's the spec generator that adds the "This section is non-normative" for sections marked as `.informative`. 

However, it sounds like you are having larger problems with spec usability. I'd suggest figuring out exactly what kinds of changes you'd like to see in one spec, user testing them to make sure the changes have the desired effect, then we can work together in changing ReSpec and/or the W3C styles.

**Comment by goodwitch** [comment]
This is really a big problem in our industry.  Most experts (that are not active in the W3C)...do NOT know this difference.  Just closing this issue makes me very, very sad for our industry.  Where can this be reported so it doesn't just get called "out of scope"?

**Comment by marcoscaceres** [comment]
@goodwitch don’t fret - we can keep discussing solutions here or elsewhere. We want to make things better so let’s keep working towards that.
