### ISSUE TITLE
Sticky TOC on the left with clickable doc links...

### ISSUE THREAD

**Issue by rchrdnsh** [w3c/tr-design#18]
Like the getting started doc for bootstrap and many others. Just scroll down a little and you will see what I mean...

http://getbootstrap.com/getting-started/#migration

They put it on the right side, but either is fine, IMHO. For long docs it is great to be able to see the TOC as a hierarchy tree with a marker of some sort showing the current position.

Thanks :-)

**Comment by tripu** [comment]
I like this one. Keeping the TOC at hand while browsing a long document is very useful.

I think there won't be good reasons _not_ to have something like that in future specs &hellip;if we can guarantee usability and accessibility.

**Comment by fantasai** [comment]
Done. It's just CSS, so not quite as fancy as the bootstrap one. Feel free to re-open once we have JS navigation enhancements in scope. ;)
