### ISSUE TITLE
How is this documented?

### ISSUE THREAD

**Issue by darobin** [w3c/tr-design#2]
Notably in how it interacts with the structures used in reports.

**Comment by svgeesus** [comment]
Agreed, the separation of content and presentation tends to be one way. Content may be styled with multiple stylesheet options; but a given stylesheet tends to assume a certain document structure and turn into a trainwreck on a random document that fails, for example, to have a div.main or whatever.
Suggest a wiki, developed alongside the actual stylesheet

**Comment by fantasai** [comment]
I'm going with a sample.html document in the stylesheets repo, that way it serves as both documentation and testcase.
