### ISSUE TITLE
#outdated-note is a weird ID to put on a link

### ISSUE THREAD

**Issue by tabatkins** [w3c/tr-design#200]
On outdated specs, like <https://www.w3.org/TR/2017/CR-css-flexbox-1-20171019/>, the "outdated spec" warning shows up - a red box with white text, and a link to the newest version of the spec.

In the markup for that panel, the link to the new spec has `id="outdated-note"`. I have no idea why. I *presume* it was added there specifically to raise the specificity of the link's selector trying to style it white. However, adding an ID to the link specifically, and with a name like `outdated-note`, doesn't make any sense to me.  If we need an ID to help with specificity, it would make more sense to go with an ID on the warning panel itself, and just use that to help target the `a`.

**Comment by plehegar** [comment]
pinging Denis on this one since I don't know if the ID is in use.
