### ISSUE TITLE
move the toc higher

### ISSUE THREAD

**Issue by r12a** [w3c/tr-design#21]
one of my main bugbears with the current TR style is the position of the toc.  If i'm deep in the document, i often want to visit a different section via the toc. Getting to the top of the doc is easy in desktop environments - it can be a bit of a pain on my iPad (i may be missing something there).

but the main thing is that when you reach the top of the page you then have to carefully scroll down a bit to find the toc.  That's the annoying bit.  

Can we not move the toc so that it's almost at the top of the page?  Maybe put it in a separate column alongside the SOTD stuff?

**Comment by fantasai** [comment]
We can't actually fix this by moving the ToC, but we've placed it on the side in wide screens, and added styles that would allow editors to add a "back to ToC" link at the bottom of the spec and have it show up along the bottom left corner.

**Comment by r12a** [comment]
i saw the proposed behaviour at TPAC and it looks good, assuming all the comments made in the meeting are adopted.
