### ISSUE TITLE
Add a darkmode version of the UNOFFICIAL DRAFT image

### ISSUE THREAD

**Issue by tabatkins** [w3c/tr-design#216]
The current UD/cg-draft image is very-light-on-white, which doesn't work on a darkmoded spec. In anticipation of launching darkmode support later, we should add a dark version of the image. (Bikeshed's experimental darkmode support already adds a custom version of the image.)

Since the current image is #fdeded on white, after some playing around while generating the Bikeshed version, I found a similar and appropriate color to be #100808 on black, producing a low-contrast (but readable due to the very large text), slightly-reddish-gray color that doesn't overly distract from the document text atop it.

(If the original image is no longer easily modifiable, I can provide the SVG source for Bikeshed's variant image. I overlaid it on top of the original to make sure the text was as close in placement and sizing as possible, tho the reliance on the system's `sans-serif` of course introduces some variation.)

**Comment by fantasai** [comment]
I have no idea where the original image came from, so SVG source would be great. I also think the text should be laid over a transparent background in any case, so we should regenerate both variants off your source.

**Comment by WebReflection** [comment]
FYI removing `--unofficial-watermark` from the `:root` already improves *a lot* readability, keeping the watermark visible.

This is GNOME Web / Safari on dark mode after ruling out that variable:

![Screenshot from 2020-11-18 15-21-26](https://user-images.githubusercontent.com/85749/99542163-02091800-29b2-11eb-9e62-1f43f4f1f8ca.png)

A whole dark mode might be useful, but maybe you can drop that variable in the meanwhile? It's really unreadable right now (Firefox on Dark Mode OS)

![Screenshot from 2020-11-18 14-33-03](https://user-images.githubusercontent.com/85749/99542260-25cc5e00-29b2-11eb-875f-140b6985d80d.png)

**Comment by fantasai** [comment]
@WebReflection AFAICT that's a Bikeshed problem. The official CG Draft styles don't have a dark mode yet. Try upgrading your copy of Bikeshed to the latest version? The output on Cookie Store API doesn't look like what I'm getting running it locally here.

**Comment by tabatkins** [comment]
So here's the markup for the Unofficial Draft logo. Swap in the pastel pink of the lightmode version for the `#100808` bit.

```svg
<svg xmlns='http://www.w3.org/2000/svg' width='400' height='400'>
 <g fill='#100808' transform='translate(200 200) rotate(-45) translate(-200 -200)' stroke='#100808' stroke-width='3'>
  <text x='50%' y='220' style='font: bold 70px sans-serif; text-anchor: middle; letter-spacing: 6px;'>UNOFFICIAL</text>
  <text x='50%' y='305' style='font: bold 70px sans-serif; text-anchor: middle; letter-spacing: 6px;'>DRAFT</text>
 </g>
</svg>
```

**Comment by fantasai** [comment]
@tabatkins OK, I refactored it a bit and adjusted the positioning. You can see the logos at

- https://fantasai.inkedblade.net/style/design/w3c-restyle/2020/logos/UD-watermark-light.svg
- https://fantasai.inkedblade.net/style/design/w3c-restyle/2020/logos/UD-watermark-dark.svg

It would be good to get a couple more people to check that the corners of the text aren't cut off on their systems. :)

**Comment by WebReflection** [comment]
@fantasai SVGs look good but it's hard to say if your commit fixed issues without seeing the whole final result.

**Comment by fantasai** [comment]
@WebReflection As I explained in https://github.com/w3c/tr-design/issues/216#issuecomment-729996624 I can't fix the document you're complaining about. The W3C style sheets don't support dark mode at all; what you're seeing in that document is the dark mode code injected as inline styles by an old version of the Bikeshed spec generator. It has to be regenerated with a more recent build which does not have this bug.

**Comment by tabatkins** [comment]
And it *has* already been regenerated, as you can see in <https://wicg.github.io/cookie-store/>.

**Comment by WebReflection** [comment]
@tabatkins yes, thanks, I can confirm GNOME Web and all others in Dark Mode now can read everything just fine.
