### ISSUE TITLE
Darkmode smoke-on-blizzard tables

### ISSUE THREAD

**Issue by bathos** [w3c/tr-design#217]
Apologies if this is the wrong repo or if this is redundant. I wasn’t sure if this comes from here, Bikeshed, or somewhere else. It looks like there are a few new-darkmode related style issues here but as far as I could tell, not this one:

![screenshot showing pale gray text on pale blue background in darkmode CSS spec](https://user-images.githubusercontent.com/6257356/94977686-d906f380-04e7-11eb-8481-fa03e729c23a.png)

All the tables seem to look like this in https://drafts.css-houdini.org/css-properties-values-api-1/ for me (Chrome).

**Comment by dontcallmedom** [comment]
cc @tabatkins

**Comment by tabatkins** [comment]
Ah, this is some bad interaction with the stylesheet that Houdini EDs link in. Sorry about that, will fix.  (This isn't relevant to tr-design, so this can be closed.)
