### ISSUE TITLE
.advisement box is inconsistent with other boxes

### ISSUE THREAD

**Issue by carmacleod** [w3c/tr-design#231]
The ".advisement" box is the only "best practices" style box that has a border on the right.
This looks inconsistent when an advisement box is right beside another type of box.

See also: https://github.com/w3c/respec/pull/2340

The following screen snapshot from the ARIA Practices Guide shows a green "note" box immediately followed by an orange "advisement" box. See the extra border line on the right. None of the other "best practices" style boxes have that line.

![image](https://user-images.githubusercontent.com/3331913/100806969-75257c00-33ff-11eb-9b31-0898d424d2ca.png)

**Comment by plehegar** [comment]
@fantasai , any objection/concern about adding a border-right here?

**Comment by carmacleod** [comment]
@plehegar 
> @fantasai , any objection/concern about adding a border-right here?

No, you misunderstood. I want the right border _removed_, not added. :)
None of the other box styles have this right border.

**Comment by plehegar** [comment]
oops. Thank you for the correction.

**Comment by fantasai** [comment]
It was intentional to have the extra border to make the advisement stand out more, and to work better for cases where it's used with short notices and centered text. But I don't mind dropping the right border if that's the preference of the ARIA folks, who use it more frequently. @carmacleod Let me know if you want me to push out this change with those considerations in mind.

**Comment by carmacleod** [comment]
Thanks, @fantasai. Will it cause a problem for short notices and centered text?
We currently have 6 instances in the ARIA Practices Guide, and may need to add more in future.
However if removing the right border will impact others, then we can probably live with it.
It looked so out of place when I first saw it, but it doesn't seem quite so bad now that I look at it again. :)

**Comment by fantasai** [comment]
@carmacleod It definitely looks a bit weird on the centered ones. ^_^ I don't think we have many of those; but if you mark up a STRONG.advisement it'll render as a centered block currently. On the others I agree with you: it's a bit surprising, but not too bad. And the second border does add a little extra emphasis to the advisement. ;)

Here's the style sheet documentation:
  https://www.w3.org/StyleSheets/TR/2016/README.html#advisement
  
Let me know what you think~

**Comment by carmacleod** [comment]
@fantasai You know, let's just leave it. I'm convinced.

I'll close out this issue. Thanks for info, and your patience. :)
