### ISSUE TITLE
make wider space to the right

### ISSUE THREAD

**Issue by r12a** [w3c/tr-design#24]
just raising this to ensure that it wasn't forgotten...

The initial proposal had the main text block centred horizontally in the window. 

During TPAC we agreed that there would be a fixed distance margin on the right of the main text block, and that if the window size was increased horizontally the max-width would therefore produce a variable and potentially much larger margin to the right, so as to better accommodate wide tables, diagrams, etc.

**Comment by fantasai** [comment]
Fixed. I think it looks a bit awkward visually, but I don't have a better practical answer to the problem of overflow (short of implementing my own layout rules in JS).

**Comment by r12a** [comment]
> I think it looks a bit awkward visually,

i think it would look better if you set margin-left: 2em on body (reducing to zero as the screen gets thin).  Could you try it?

**Comment by fantasai** [comment]
Okay, I figured out a way to create centered space in the CSS, so I've mapped that to .overlarge and the figure markup, and recentered the text (which looks a lot better). And since we have JS as an option now with the fixup script, I'm adding .overlarge wrappers automatically for table elements--this is also for handling bug #38. Take a look and let me know if this works for you.

http://fantasai.inkedblade.net/style/design/w3c-restyle/2016/sample#overlarge
http://fantasai.inkedblade.net/style/design/w3c-restyle/2016/sample#property-index

**Comment by iherman** [comment]
It does. Thank you.

**Comment by r12a** [comment]
I'm seeing this on Firefox 43 on Mac OS X 10.11. (Table and caption right aligned, but caption further to the right.) Any idea why?

![screen shot 2016-01-15 at 07 53 09](https://cloud.githubusercontent.com/assets/4839211/12348377/9c8cd302-bb5e-11e5-84b2-12d72f28360a.png)

**Comment by fantasai** [comment]
No idea why. That looks super weird, alignment-wise. Works fine on Linux. Try shift-reload?
The wrapping is due to an error measuring inline content in Gecko. I'll take a look, but that's a separate issue.

**Comment by r12a** [comment]
don't know whether you did something, but it looks ok now. Strange. Thanks.

**Comment by r12a** [comment]
wait a moment .... !  I guess i'm now seeing the expected effect in wide windows too for the first time. So now the text column is centred except when you have wider elements sticking out on both sides at various places?  I think that's horribly ugly.  It also makes it hard to spot headings, if you have more than one table or wide item on either side.  

Please switch it back.  It was looking pretty much ok before. I was suggesting just a smidgen more space to the left, not this.  Sorry, i think this is awful.  If it's too hard to add the extra 2em, then i think it will be much better left as it was.

**Comment by fantasai** [comment]
I think this is a point on which reasonable people can agree: imho the left-aligned content block looks bad, and centering is better. :) We can get more opinions on this and see what other people think.

My hope is that the 50em max-width will encourage people to notice when their content is really wide and, aside from tables which can't really be helped, try to make sure it all fits within the column.

**Comment by fantasai** [comment]
Tab notes that left-aligning looks better when the ToC is popped in, so I'll see about switching it to left-alignment at least in that case.

**Comment by fantasai** [comment]
Done. Let me know if I should do something similar when the ToC is not there. Atm I think it looks more balanced centered.
