### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by fantasai** [w3c/tr-design#241]
There's been two PRs so far that tried to add Dark Mode support, https://github.com/w3c/tr-design/pull/184 from @jakubklimek and https://github.com/w3c/tr-design/pull/202 from @tabatkins but we haven't merged any of them into the main line because swapping a spec that isn't expecting it into dark mode can make things unreadable.

Originally we were thinking to plan out the addition of Dark Mode with plenty of advance warning so that editors would have time to fix their specs before we deployed it across all of w3.org/TR, and to only apply it to specs published after that deploy date, with the hope that all the specs that got published from that point in time forward would be compatible with Dark Mode... and were waiting for a good time to prepare for and apply that cut-off.

But now I'm thinking what might make more sense is to add a separate dark.css file which editors can selectively choose to add to their spec, presumably after verifying that their diagrams and any custom styling are compatible with it. We could deploy that basically immediately, and the editors can opt in whenever they're ready.

Relatedly, we probably want a way for users to flip the colors on/off, and to have that persist across w3.org/TR so that users can opt into or out of dark mode for our specs generally. (Certain vendors seem to conflate the idea of “I want a dark OS UI” with “I want all content on the Web to be dark”...) I'm not sure how to implement that, though.

**Comment by fantasai** [comment]
@deniak If this sounds like a reasonable plan to you, lmk and I'll copy the latest Bikeshed dark mode variants of our color variables into a new dark.css file.

@marcoscaceres Let me know if that seems like a workable plan for ReSpec also, and if you think we need anything else?

Also if anyone's good at coding up persistent switches in JS, could use some help with that...

**Comment by deniak** [comment]
This would kind of break consistencies between the specifications but I'm not sure this is such a big deal. I'm thinking we could allow this for WDs only at the beginning.

/cc @plehegar

**Comment by tabatkins** [comment]
> Also if anyone's good at coding up persistent switches in JS, could use some help with that...

This can be accomplished with a real simple script that stores data in a cookie or LocalStorage. It's just a couple lines of JS, and I already wanted to write one for Bikeshed *in general*, so I can contribute something.

**Comment by fantasai** [comment]
@deniak I would allow it for all specs. It would be weird if they lose a nice readability feature once they are more mature!

**Comment by deniak** [comment]
> @deniak I would allow it for all specs. It would be weird if they lose a nice readability feature once they are more mature!

My fear is actually that there's an issue with the style and editing an already published REC can be tricky. But our policy allows to fix some visible style issues so this might not be such a problem.

**Comment by plehegar** [comment]
We could allow it for all specs, assuming we would be prompt at reacting if an issue comes up.

**Comment by deniak** [comment]
@fantasai could you provide the CSS for the dark mode? I'll try to use it on one of our spec and add all the necessary javascript to toggle it. Then if it looks good to all of you, we can schedule a release date.

**Comment by fantasai** [comment]
> My fear is actually that there's an issue with the style and editing an already published REC can be tricky.

@deniak I think there's a misunderstanding, reread the initial comment? The plan is not to add them to all existing publications, only to provide the stylesheet and JS to allow new publications (of any status) to include a dark mode.

The link, btw, would look something like

```
<link href="https://www.w3.org/StyleSheets/TR/2016/W3C-WD" rel="stylesheet" type="text/css">
<link href="https://www.w3.org/StyleSheets/TR/2016/dark" rel="stylesheet" type="text/css" media="(prefers-color-scheme: dark)">
```

where the second line is optional. Many specs have images or custom styling that assumes a light background, so individual specs need to opt in explicitly.

I'll draft a PR to add the CSS file. You'll want to create the appropriate JS based on whether or not the dark mode style sheet is included in the source or not.

**Comment by marcoscaceres** [comment]
> You'll want to create the appropriate JS based on whether or not the dark mode style sheet is included in the source or not.

Probably want ReSpec and Bikeshed to handle that, right?

**Comment by deniak** [comment]
sorry I wasn't clear. Yes, the idea is to only allow the feature to specs published after a specific date. To go forward, I want to make a **copy** of one of our existing spec so we can test the JS and the CSS first.
Once we all agree it's ready, ReSpec and Bikeshed can offer an option to include the CSS/JS.

**Comment by fantasai** [comment]
@marcoscaceres For the toggle? I think it should probably just be included in fixup.js and trigger on presence of the `<link>`. That way any spec that includes dark.css will get the ability to toggle the style, not just the ones generated by respec+bikeshed.

**Comment by marcoscaceres** [comment]
> @marcoscaceres For the toggle? I think it should probably just be included in fixup.js and trigger on presence of the `<link>`. 

Was thinking to opt-into the inclusion of dark.css. Feels like a burden to ask Editors to manually include the `<link>` above. 

Happy for fixup to handle the toggle. That be great!

**Comment by fantasai** [comment]
@marcoscaceres Oh, yes, of course. :) You might also add a feature to occasionally trigger random modes on EDs so editors notice if their colors break in the mode they aren't usually using... ;)

**Comment by marcoscaceres** [comment]
heh, I like where this is going ... mauahahaha :D

**Comment by fantasai** [comment]
Ok, major question here: Bikeshed's dark mode rules have `img, svg { background: white; }` in dark mode to make sure that images with transparent backgrounds remain visible.

Should we do the same thing here and have editors override it back to transparent as appropriate, or should we leave that rule out and let editors add it in as needed? Unlike Bikeshed, we are opt-in for dark mode styling. But it's also an easy thing to screw up.

**Comment by tabatkins** [comment]
Talked this over with Elika today, and I think we should keep the `background:white` on `img`. It's *very* easy to accidentally write an SVG that looks great in light mode (because it's black lines on a transparent bg) then fails on dark mode. If it's documented how to override it when necessary (a quick `style="background:transparent"`), I think it's better for readers to have the line still in by default.

I'm not as convinced about doing the same for inline SVG.

**Comment by deniak** [comment]
I just deployed the stylesheet and script so anyone can now enable the dark mode for their specifications.
I understand @sidvishnoi is working on [adding a config option in respec](https://github.com/w3c/respec/pull/3236).
@tabatkins, do you have any recommendation to enable it for bikeshed documents?

**Comment by SamB** [comment]
@fantasai wrote:
> @marcoscaceres Oh, yes, of course. :) You might also add a feature to occasionally trigger random modes on EDs so editors notice if their colors break in the mode they aren't usually using... ;)

If you were to actually do that, it would be important to inform the user why this is happening, and maybe even let them skip it if they aren't inclined to file such bugs at present (maybe they just don't file bugs, maybe they don't want to report that kind of thing on their phone, maybe it's nighttime and light mode is just too light). Otherwise, the people you actually *want* checking this - those inclined to yak-shaving - will probably just get it to "work" again instead of testing the other mode, and will therefore probably not spot any issues not on whatever screenful of spec they landed on.
