### ISSUE TITLE
Link from https://w3c.github.io/tr-design/ to the sample spec

### ISSUE THREAD

**Issue by jyasskin** [w3c/tr-design#246]
Right now, if I get to https://w3c.github.io/tr-design/, I have to click the "Improve this page" link at the bottom, then the 'code' tab in github, in order to find the link to https://w3c.github.io/tr-design/src/README. It'd be nice to have a direct link.

**Comment by plehegar** [comment]
hi @jyasskin , with the Process 2021 coming up, I'm in the process of updating our templates again. I'll make sure gets resolved as part of that.
