### ISSUE TITLE
Collapse SOTD also

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/tr-design#249]
Responding to https://w3c.github.io/tr-design/p2021mockup/ per https://www.w3.org/mid/92302110-ff38-05db-4720-1a83ab9d7708@w3.org. I think putting the top boilerplate in <details> makes it a lot easier to get into the content. However, the real content is still "below the fold". I suggest the SOTD also be put in a <details>, so there's room for the first "real" section to show after the abstract at least on desktop-sized screen.

**Comment by fantasai** [comment]
SOTD needs to be ripped apart and redistributed, not put into a details element.

**Comment by plehegar** [comment]
Indeed, we cannot collapse the SOTD. Some of the text, like the patent policy must be visible.
