### ISSUE TITLE
Horizontal scrolling

### ISSUE THREAD

**Issue by martinthomson** [w3c/tr-design#25]
In Firefox nightly [the sample](http://fantasai.inkedblade.net/style/design/w3c-restyle/2016/sample) scrolls a little horizontally.

**Comment by fantasai** [comment]
Yes, this is because the property index table at the bottom overflows. I don't have a better solution to that than to let it overflow, it's kindof a useful table to be able to access. :)

**Comment by martinthomson** [comment]
I suppose that you considered `overflow-x: auto` for that and decided against it?  Limiting the horizontal scrolling to just that table would be nice.  Otherwise, I'd just remove it from the sample.  Unless this is a common feature of CSS specs, that is.

**Comment by fantasai** [comment]
Almost all CSS specs have a property index table at the end, yes. I think if individual groups want to put scrollers on overflowing tables, that's a nice experiment, but I don't think I want to introduce that at the W3C level unless we're sure it's the right answer for everybody. One of the disadvantages of individual scrollers is that often you don't have the event focus in the right place to scroll them, but when there's only one document scroller that's never a problem. Another issue is that on a wider screen, you will see more of the table if we don't limit its size and put an individual scroller on it, but if we limit it to match the max-width, you can't take advantage of the wider screen size to see more of the table.
