### ISSUE TITLE
Status Description Phrasing wrt Patent Policy

### ISSUE THREAD

**Issue by fantasai** [w3c/tr-design#250]
“Publication as a Candidate Recommendation does not imply endorsement by the W3C Membership. A Candidate Recommendation Snapshot has received wide review, is intended to gather implementation experience, and _participants granted Royalty-Free IPR licenses for implementations_. ”

I think this phrasing is poor grammar and confusing, and suggest instead something like “and guarantees certain Royalty-Free IPR licenses for implementations”.

Reasons it's confusing: “participants” is vague. Participants of what? Even the Process and Patent Policy define it differently. Also wrt the verb “granted”, the Patent Policy requires the licenses to be granted, but whether they have been granted at the point of publication before the company has actually drafted one up or not is... debatable. Let's not get into it.

Reasons it's poor grammar: the "and" is joining a list of predicates (the subject being “A Candidate Recommendation Snapshot”), but the last item in that list has a subject as well and is a full clause. This is bad form.

CC @plehegar @wseltzer

**Comment by fantasai** [comment]
Last point: If this phrase is in the CRS STOD statement, it definitely belongs in the REC SOTD statement, too. Like, I don't care if we mention it, but if we do they need to be mentioned equally.

**Comment by wseltzer** [comment]
Let's keep iterating. 

"... A Candidate Recommendation Snapshot has received wide review and is intended to gather implementation experience. Group participants have committed to royalty-free patent licensing for implementations. "

**Comment by fantasai** [comment]
Works for me. If we want to keep it all one sentence, I guess it could be 

“A Candidate Recommendation Snapshot has received wide review, is intended to gather implementation experience, and has [commitments  from Working Group members to Royalty-Free IPR licensing](https://www.w3.org/Consortium/Patent-Policy-20200915/) for implementations.”

(link goes to top of Patent Policy; I'm a little uncomfortable linking just to the one chapter, since understanding who committed what requires the whole thing)

**Comment by wseltzer** [comment]
I prefer "patent" to "IPR" (since that's what the Patent Policy covers)

**Comment by fantasai** [comment]
@wseltzer Ah, right, miscopied when I merged the two wordings. :) I agree.

“A Candidate Recommendation Snapshot has received wide review, is intended to gather implementation experience, and has commitments from Working Group members to royalty-free patent licensing for implementations.”
