### ISSUE TITLE
respec related conflicts with examples?

### ISSUE THREAD

**Issue by iherman** [w3c/tr-design#26]
Consider the image below. It is a document generated through respec, using the standard 'example' class. When generated through respec, (see the [original](http://www.w3.org/TR/2015/CR-tabular-metadata-20150716/#h-annotating-tables)) there is only one vertical line on the left, when replacing base with the new version we get two. 

/Cc: @halindrome @plehegar 

![example](https://cloud.githubusercontent.com/assets/520723/11083377/24e25636-882f-11e5-92c8-9e9795911d4c.png)

**Comment by r12a** [comment]
I believe it's because you set the example class on the pre element as well as the div element that contains it. It seems that this redundancy is generated by respec. I would certainly think that one example class should be sufficient.

**Comment by iherman** [comment]
The original, respec code is:

```
      <pre class="example highlight">
{
  "name": "inventory_date",
  "titles": "Inventory Date",
  "dc:description": "The date of the operation that was performed.",
  "datatype": {
    "base": "date",
    "format": "M/d/yyyy"
  }
}
      </pre>
```

Ie, it is definitely respec that adds both. But one would expect that changing the style sheet would not lead to such differences anyway...

**Comment by halindrome** [comment]
Hmm.  We _could_ change respec so that when it wraps the example in a div
it removes the class example from the pre...  but that feels weird.

On Wed, Nov 11, 2015 at 2:33 AM, Ivan Herman notifications@github.com
wrote:

> The original, respec code is:
> 
> ```
>   <pre class="example highlight">
> ```
> 
> {
>   "name": "inventory_date",
>   "titles": "Inventory Date",
>   "dc:description": "The date of the operation that was performed.",
>   "datatype": {
>     "base": "date",
>     "format": "M/d/yyyy"
>   }
> }
>       </pre>
> 
> Ie, it is definitely respec that adds both. But one would expect that
> changing the style sheet would not lead to such differences anyway...
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/w3c/tr-design/issues/26#issuecomment-155703229.

## 

Shane McCarron
halindrome@gmail.com

**Comment by fantasai** [comment]
While I can work around this ReSpec issue in the style sheet sort-of (by replacing all occurrences of 
.example' with ':not(.example) > .example', which will catch most cases of this ReSpec output), it does seem redundant to me to have the example class on both elements. I would prefer that ReSpec remove the nested 'example' class. On the off chance you need to style PRE blocks inside examples specially, it's very easy to do with '.example pre'.

Let me know what you think.

**Comment by halindrome** [comment]
I addressed this in my support for your stylesheets.

On Mon, Nov 30, 2015 at 1:55 PM, fantasai notifications@github.com wrote:

> While I can work around this ReSpec issue in the style sheet sort-of (by
> replacing all occurrences of
> .example' with ':not(.example) > .example', which will catch most cases of
> this ReSpec output), it does seem redundant to me to have the example class
> on both elements. I would prefer that ReSpec remove the nested 'example'
> class. On the off chance you need to style
> 
>  blocks inside examples specially, it's very easy to do with '.example pre'.
> 
> Let me know what you think.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/w3c/tr-design/issues/26#issuecomment-160740560.

## 

Shane McCarron
halindrome@gmail.com

**Comment by fantasai** [comment]
Excellent. I'll close the issue then.
