### ISSUE TITLE
W3C-ED.css' --w3c-state-text-text is always set to black

### ISSUE THREAD

**Issue by rakuco** [w3c/tr-design#284]
https://w3c.github.io/ambient-light/ and a handful of other Devices and Sensors WG specs use Bikeshed, which automatically generates some CSS that differs between `prefers-color-scheme: dark` and `prefers-color-scheme: light`. `W3C-ED.css` does not seem to play well with this though, as it ends up generating black text on a black background when a UA's color scheme is set to `dark`.

See the following screenshots showing the difference between `light` and `dark` mode:

![light-mode](https://user-images.githubusercontent.com/36417/145083089-cfee6d45-b578-4048-8365-962b3ae7f364.png)

![dark-mode](https://user-images.githubusercontent.com/36417/145083107-fab11421-7306-418a-9751-46c18d06683f.png)

I tried to manually add `dark.css` but it did not make any difference, as it does not change `--w3c-state-text-text`'s value.

**Comment by fantasai** [comment]
Thanks for the report. Opened PR #285 hopefully @deniak can get it sorted.

**Comment by deniak** [comment]
It's now merged and I see the spec now appears correctly.

**Comment by rakuco** [comment]
Thank you for fixing this so quickly!
