### ISSUE TITLE
W3C specifications use a 2-column view, which is not universally accessible

### ISSUE THREAD

**Issue by MarjaE2** [w3c/tr-design#287]
I visited https://drafts.csswg.org/web-animations-1/ because web animation poses way too many accessibility problems. And can make me very sick.

Following current web design tends, it has navigation in one column, and the body in another column, and has each scroll separately. This type of animation, one column scrolling without another, can trigger migraines in people with visual vertigo/visually-induced dizziness, such as some concussion survivors. So people who get sick from animation may not be able to raise accessibility concerns.

I visited https://drafts.csswg.org/web-animations-1/ but I assume other drafts are also affected.

**Comment by dontcallmedom** [comment]
(not a solution to the issue which needs to be addressed in the style sheet, but as a temporary workaround, the second column disappear in narrow-enough windows)

**Comment by dontcallmedom** [comment]
would it make sense to use the `prefers-reduce-motion` feature to switch to having the two columns scroll together?

**Comment by MarjaE2** [comment]
That makes sense to me.

For user-end workarounds, relying in page down instead of scrolling, or reducing frame rate to no more than 1 frame/second, can help. I find it helpful to push any boundary between scrolling and non-scroling elements close to the edge of the screen, and using a smaller window doesn't help with that.

**Comment by plehegar** [comment]
Makes sense to me as well. @deniak , is that something you'll like to try or should I look in doing it?

**Comment by deniak** [comment]
> Makes sense to me as well. @deniak , is that something you'll like to try or should I look in doing it?

I'll give it a try this week but what are the expectations regarding the scrolling? The TOC and the content of the spec have different heights so do you expect the scrolling rate to be the same for the 2 columns or proportional to the height of the sections?
I'm assuming it's the second option as the first one will not really solve the issue but it feels a bit weird to have different scrolling speeds on the same page as well.

**Comment by dontcallmedom** [comment]
I think the first option ("scrolling rate the same for the 2 columns") solves the problem actually

**Comment by deniak** [comment]
Ok, I gave it a try and you can see the result [here](https://cdn.statically.io/gh/w3c/tr-design/2-column-scroll/src/README.html). Please comment on [the PR](https://github.com/w3c/tr-design/pull/293) if you have any remarks.

**Comment by MarjaE2** [comment]
Works great for me!

**Comment by MarjaE2** [comment]
.... Until the left column runs out.

**Comment by dontcallmedom** [comment]
@MarjaE2 unfortunately https://cdn.statically.io/gh/w3c/tr-design/2-column-scroll/src/README.html no longer reflect the latest version of https://github.com/w3c/tr-design/pull/293 which I think solves this; we'll ping you as soon as we have a proper rendition of that latest version
