### ISSUE TITLE
Blue line under W3C logo

### ISSUE THREAD

**Issue by r12a** [w3c/tr-design#29]
When applying the new style to 
http://www.w3.org/TR/2015/WD-international-specs-20151020/
and other docs, i see a blue line under the W3C logo at the top right of the doc.

Will that be automatically fixed for the new style?
![screen shot 2015-11-11 at 07 32 29](https://cloud.githubusercontent.com/assets/4839211/11086186/72727496-8846-11e5-9848-f6469e08f89c.png)

**Comment by LeaVerou** [comment]
It seems that the logo doesn't have a class of `logo`, which seems to be causing this…

**Comment by fantasai** [comment]
Should be fixed now. Let me know if it's not.

**Comment by r12a** [comment]
It doesn't seem to be. But then i may be linking to the wrong version of the style sheet. Which one are we supposed to be linking to?  (And can we make it a single authoritative location that is on GH or the W3C site?)
