### ISSUE TITLE
What is the backwards compatibility story?

### ISSUE THREAD

**Issue by darobin** [w3c/tr-design#3]
If we plan for the styles to be backwards compatible in perpetuity, we need a strategy if the design is going to evolve more than a little bit.

We know from experience that updating styles on unsuspecting drafts will break things, and there are too many to check.

One option is that when new, larger changes are made they are keyed off a special class that drafts must use in order to opt into the new style. (I think this is my preferred approach.)

Another option is to have releases (hopefully not too often) and major ones can break things but are opted into.

**Comment by plehegar** [comment]
My suggested rule 1 is: New styles are only applied to future documents.

As a consequence, there are no backwards compatibility issues.

**Comment by plehegar** [comment]
More on rules: https://github.com/w3c/tr-design/blob/gh-pages/README.md

**Comment by fantasai** [comment]
Closing this as fixed, by plh's policy.
