### ISSUE TITLE
Sheep appearing beneath the copyright statement

### ISSUE THREAD

**Issue by r12a** [w3c/tr-design#31]
See the image (taken from http://www.w3.org/TR/2015/WD-international-specs-20151020/ with the stylesheet link pointing to the new style sheet)

![screen shot 2015-11-11 at 07 36 21](https://cloud.githubusercontent.com/assets/4839211/11086231/ecc07694-8846-11e5-8b0f-eb0e2ba76191.png)

**Comment by fantasai** [comment]
Should be fixed now.
