### ISSUE TITLE
Where are the current styles?

### ISSUE THREAD

**Issue by tabatkins** [w3c/tr-design#328]
This repo only contains the 2015 versions of the styles, but we're currently using more modern versions. Where are those located? Where should I report bugs on them?

(There's an error with how ToC links are styled - when unhovered they apply a 1px transparent bottom border, while when hovered they apply a 3px colored border and a -2px bottom margin. They *intend* these two to have identical layout effects, but since borders round to the nearest device pixel that's not guaranteed; on my screen the two states differ by one device pixel. We should be using the 3px/-2px layout in both states, and just change the color on hover.)

**Comment by fantasai** [comment]
They're in this repo afaict? https://github.com/w3c/tr-design/tree/gh-pages/src

Should be the same as those living in https://www.w3.org/StyleSheets/TR/2021/ unless there's some kind of problem.

**Comment by tabatkins** [comment]
...huh, for some reason I didn't look there, only in the `releases` folder.

**Comment by tabatkins** [comment]
I'll drop the edit in a PR, then.
