### ISSUE TITLE
Images constrained to be blocks?

### ISSUE THREAD

**Issue by r12a** [w3c/tr-design#33]
I applied the new styling to 
http://www.w3.org/TR/2015/WD-clreq-20150730/#h-examples_of_zhuyin_annotations

Previously the four images in the figures were displayed side by side, which helps significantly in comparing the various figures. Here is a snap:

![screen shot 2015-11-11 at 07 54 49](https://cloud.githubusercontent.com/assets/4839211/11086542/125ebce6-884a-11e5-9f42-7347181ba4be.png)

Now the images are shown as blocks, which spoils the intended effect.

![screen shot 2015-11-11 at 07 55 18](https://cloud.githubusercontent.com/assets/4839211/11086552/273146d4-884a-11e5-8841-ff833132dfb9.png)

Why are the images forced to be block items?

Note also, btw, that the positioning of the list item counter now is rather confusing compared to the original.

**Comment by fantasai** [comment]
Because in our specs the images were always individual block-level items, so we styled them as blocks. :) I switched the style sheet to not do that, and use text-align for centering instead. Let me know if this helps.

**Comment by r12a** [comment]
thanks. The images now can sit side-by-side. They still need some styling, however, to allow them to expand past the 50em limit, otherwise only three will fit alongside each other. I'm wondering you may be coming up with a solution to that, or whether i need to roll it myself.

**Comment by fantasai** [comment]
That would be a duplicate of Issue 27, no? I think the original issue here is fixed.

**Comment by r12a** [comment]
i think .overlarge would indeed address this. Thanks.
