### ISSUE TITLE
Images for invisible, whitespace, and combining characters

### ISSUE THREAD

**Issue by xfq** [w3c/tr-design#340]
https://w3c.github.io/tr-design/src/README#unicode-codepoints

The stylesheet does not include support for images in the character template. See https://www.w3.org/TR/international-specs/#example-example-of-a-character-reference-with-an-image

**Comment by xfq** [comment]
Previous discussions:

@fantasai [wrote](https://github.com/w3c/tr-design/pull/323#issuecomment-1716599231):

> @aphillips What's the benefit of adding images for invisible characters? Is it really worth the cost to a) creating the images b) tracking the images with the specification text c) complicating the stylesheet and markup patterns and d) disrupting the paragraph line spacing?

-----

@aphillips [wrote](https://github.com/w3c/tr-design/pull/323#issuecomment-1717033390):

> Regarding images, @r12a has been using them for some time and feels that they provide better usability. The images helps make invisibles clearer, at least in some cases. An argument can be made that the sometimes detract from the page and that it is a maintenance headache (especially with regard to echidna configuration), but it is somewhat optional. We might make it clearer that it is up the discretion of the author to use images if they so desire and to spell out the maintenance tradeoff.

-----

@xfq [wrote](https://github.com/w3c/tr-design/pull/323#issuecomment-1717561364):

> It is not only useful for invisible characters, but also useful for combining characters. If the font doesn't support display with a dotted circle (`U+25CC DOTTED CIRCLE`), then an image is needed.

-----

@fantasai [wrote](https://github.com/w3c/tr-design/pull/323#pullrequestreview-1623905748):

> @aphillips OK, I'm going to suggest we tackle that question separately.

**Comment by r12a** [comment]
We (the i18n WG) feel that it _is_ certainly worth the (very minimal) cost to create such images, that the stylesheet and markup patterns are not complicated and have been established already, and we have taken pains to ensure that the images can be added without disrupting the paragraph line spacing.

We have been working on and discussing this small piece of markup for a long time now (far too long) and the i18n working group has achieved a consensus about how to proceed.  I don't think it is reasonable to jump in and block this without having been involved in the discussions in a timely way, and even less so to allow through a subset of the markup without consultation.  If an author thinks that providing images is not useful, then they don't need to provide them in their content. But let's not block their use by those who do think they are useful.  The i18n WG already finds it useful to use such images in several of its documents.

**Comment by aphillips** [comment]
Should we just prepare a fresh pull request? I can reference this issue in the PR.

**Comment by r12a** [comment]
@aphillips i just noticed a typo in section 2.4.3.2

> `</cdode>` should be `</code>`

**Comment by aphillips** [comment]
@r12a Thanks. See new PR (since this one is merged)
