### ISSUE TITLE
.dark class for dark mode

### ISSUE THREAD

**Issue by xfq** [w3c/tr-design#349]
It would be useful to add a `.dark` class via fixup.js when the spec is in dark mode, because many specs have customized styles and we can adapt the styles using media query using `:not(.dark)` in specs.

/cc @deniak

**Comment by deniak** [comment]
I've submitted a PR to add a class `darkmode`: https://github.com/w3c/tr-design/pull/350

**Comment by xfq** [comment]
There seems to be a bug. My system is in light mode and I selected auto, but there is still a `darkmode` class on `body`.

**Comment by deniak** [comment]
Fixed by #352
