### ISSUE TITLE
Effect of github.io on the display of the new style?

### ISSUE THREAD

**Issue by iherman** [w3c/tr-design#35]
I was looking at:

https://w3c.github.io/csvw/html-note/index.html

The strange situation is that
- Looking that file with Chrome, Firefox, or Safari (on a MacOS) the styling is clearly incomplete; the 'Editors draft' banner is missing, and the margins of the page are also not set
- Looking at the same file through localhost on my machine, I see the new TR style appearing (with TOC on the left)

I wonder whether this is a CORS like issue or something specific to github. Or possibly respec (that file is done via respec).

But, taking into account that it has become the practice to refer to the github.io file as the "editor's draft" in the header of our publications, this should be taken care of...

/Cc: @gkellogg @halindrome @marcoscaceres

**Comment by gkellogg** [comment]
My browser debugger shows that a script was prevented from running:

> [blocked] The page at https://w3c.github.io/csvw/html-note/index.html was not allowed to run insecure content from http://fantasai.inkedblade.net/style/design/w3c-restyle/2016/W3C-ED.

**Comment by marcoscaceres** [comment]
@fantasai's certificate is busted, so we can't switch to TLS until she fixes it.

**Comment by gkellogg** [comment]
Fortunately, GitHub doesn't insist on TLS: http://w3c.github.io/csvw/html-note/index.html.

**Comment by tripu** [comment]
Not an issue, I think, as it works using HTTP.

We could also [switch protocols for `fantasai.inkedblade.net` in ReSpec](https://github.com/w3c/respec/blob/develop/js/w3c/style.js#L44) depending on the protocol of the source document.

**Comment by halindrome** [comment]
Oh, you know, copy the files over to a w3c server?

On Sun, Nov 29, 2015 at 9:42 PM, tripu notifications@github.com wrote:

> Not an issue, I think, as it works using HTTP.
> 
> We could also switch protocols for fantasai.inkedblade.net in ReSpec
> https://github.com/w3c/respec/blob/develop/js/w3c/style.js#L44
> depending on the protocol of the source document.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/w3c/tr-design/issues/35#issuecomment-160508622.

## 

Shane McCarron
halindrome@gmail.com

**Comment by marcoscaceres** [comment]
On November 30, 2015 at 7:37:01 AM, Gregg Kellogg (notifications@github.com) wrote:

> Fortunately, GitHub doesn't insist on TLS: http://w3c.github.io/csvw/html-note/index.html.  

We should do our best to serve encrypted content. It's not good form to do otherwise (mostly because it makes a mess for those users that default to TLS and for those wish that want to retain some anonymity).

**Comment by marcoscaceres** [comment]
On November 30, 2015 at 3:50:07 PM, Shane McCarron (notifications@github.com) wrote:

> Oh, you know, copy the files over to a w3c server?

Yes, this would be good.

**Comment by tripu** [comment]
> Oh, you know, copy the files over to a w3c server?
> 
> > Yes, this would be good.

I'm not sure about that (if I understand you correctly). Keeping these files updated in 3 locations (here on GH + `fantasai.inkedblade.net` + `w3.org`) would be a mess.

As GH is the place where this redesign is happening and everything is served already by GH via HTTPS, here goes another suggestion: have ReSpec use gh-pages instead of @fantasai's own copy of the files; ie in this particular case: [`https://w3c.github.io/tr-design/src/W3C-ED.css`](https://w3c.github.io/tr-design/src/W3C-ED.css) instead of [`http://fantasai.inkedblade.net/style/design/w3c-restyle/2016/W3C-ED`](http://fantasai.inkedblade.net/style/design/w3c-restyle/2016/W3C-ED).

**Comment by marcoscaceres** [comment]
On November 30, 2015 at 4:05:10 PM, tripu (notifications@github.com) wrote:

> > https://w3c.github.io/tr-design/src/W3C-ED.css instead  

Yep, that works :D Let's roll with that. I wasn't sure what the authoritative ones was going to be.

**Comment by marcoscaceres** [comment]
Ok, sent a PR: https://github.com/w3c/respec/pull/528

**Comment by fantasai** [comment]
The authoritative copy is this repository. :) I only put them on my server so people could see them live. Note that the way these files are set up, they require a server with MultiViews enabled.

**Comment by halindrome** [comment]
Hmm - and is github such a repo?  'cause we just changed ReSpec to point to github

**Comment by r12a** [comment]
Why do you need multiviews for CSS files? Form factor?

**Comment by fantasai** [comment]
W3C content-negotiates most things, including both the CSS files and, perhaps more relevantly, the images linked from them. This is why we could replace the PNG files with SVG ones without any problem, for example.

**Comment by fantasai** [comment]
Sorry, closed issue by accident... Github.io is not able to serve up with content negotiation the way the W3C server does, no.

**Comment by tripu** [comment]
Hum, good thing w3c/respec#528 isn't merged yet, then&hellip;

> @fantasai's certificate is busted, so we can't switch to TLS until she fixes it.

Then: either @fantasai replaces her certificate, we stick to HTTP for now, or I upload a copy of the files to `w3.org` and update it daily (say). The latter I don't like, because of the redundancy and the possible confusion I mentioned before.

WDYT?

**Comment by fantasai** [comment]
If there's a good place to host them on w3.org, I think that's best. You can set up a cron job to pull from the github repo at a smaller time interval, even. And I'm happy to set up redirects from fantasai.inkedblade.net to the appropriate location on w3.org. If that's awkward, I can look into getting a certificate for inkedblade.net (it doesn't even have one) or ask plinss to host on csswg.org.

**Comment by fantasai** [comment]
It looks like plh fixed the cert issue by copying them over onto http://www.w3.org/2016/01/ Let me know if there's still an issue here.

**Comment by halindrome** [comment]
Seems okay so far

**Comment by plehegar** [comment]
closing this one. If you disagree, reopen and indicate where the problem remains.
