### ISSUE TITLE
Use fractional rem rather than em for "pre, code, a.property"

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/tr-design#37]
The rule that sets font-size to 0.9em in base.css for "pre, code, a.property" means that a `<a>` element in a `<code>` element in a `<pre>` element gets that rule applied 3 times, which makes it tiny and breaks space indentation between a `<code>foo</code>` and a `<code><a>bar</a></code>` — among other things, this makes WebIDL code managed by ReSpec look disaligned.

Using `rem` instead of `em` should fix this.

**Comment by fantasai** [comment]
Fixed by adding pre code, code code { font-size: 100%; }; the rem option would break code in headers, etc. ;)
