### ISSUE TITLE
Larger back to top and show/hide sidebar buttons

### ISSUE THREAD

**Issue by yatil** [w3c/tr-design#41]
Those buttons are extremely hard to hit on mobile (iPhone 6s Plus) and are only 22⨉22px large. The recommended size is 44⨉44px, so that is a quarter of the space they should have.

**Comment by fantasai** [comment]
From bug #39 : “I would also like to be able to see the funny arrow-thing at the bottom left of the page, but when I'm tabbing I'm almost always on a link and the URL the browser displays is just larger than the arrow (so if the arrow were either a bit bigger or moved up a bit from the bottom, it could be seen). I also have to discover what these arrows do as they're kinda mystery-meat-- unless the title that is supplied to mouse users could be added on focus?
`arrow-thingie:focus:after {
    display: whatever; content: attr(title); 
    //and some styles to put it in a useful place}`
”

**Comment by StommePoes** [comment]
I know the 44px was a known minimum but it's good to keep this in mind:
https://lists.w3.org/Archives/Public/public-mobile-a11y-tf/2015Dec/0032.html

But anyway, muchos YESes to this issue.

**Comment by marcoscaceres** [comment]
Agree. Don't use pixels, but use either mm or cm (i.e., values that are dpr independent).

**Comment by fantasai** [comment]
Marcos, px are tied to mm in a fixed ratio. See https://www.w3.org/TR/css-values-3/#absolute-lengths (This didn't used to be the case: they used to be based on the visual angle while the others were measured on-screen. But the Web assumes 96dpi, so we unfortunately had to change that... In any case, px have never been defined as 1 device pixel.)

**Comment by marcoscaceres** [comment]
Argh, thanks for the clarification. I hate the web😤 now I don't know what unit of measurement to use anymore 😭

**Comment by fantasai** [comment]
Some combination of vh, vw, and rem is usually a good idea. :)

**Comment by fantasai** [comment]
I've updated the style sheet to address to try to address these comments.
http://fantasai.inkedblade.net/style/design/w3c-restyle/2016/sample
Please play with it and file further issues as necessary.

...Note, however, there's one issue I can't easily fix: the blank link text of the unfocused link when the other one is focused by keyboard. Maybe I'll come up with a solution tomorrow. Or maybe it'll just look a bit awkward for now. :/
