### ISSUE TITLE
Use different icons/glyphs for the show/hide toc and back to top links

### ISSUE THREAD

**Issue by yatil** [w3c/tr-design#42]
The show hide toc arrow left/right has an unclear function when looking at it for the first time. I would prefer the abbreviation TOC for it.

The back to top arrow is very thin, it could take a thicker arrow to make the purpose really clear.

**Comment by fantasai** [comment]
Both arrows have a ToC function... One goes up to the ToC without popping it out, and the other one slides it out. I'll think about what to do...

**Comment by fantasai** [comment]
I've updated the style sheet to address to try to address these comments.
http://fantasai.inkedblade.net/style/design/w3c-restyle/2016/sample
Please play with it and file further issues as necessary.

...Note, however, there's one issue I can't easily fix: the blank link text of the unfocused link when the other one is focused by keyboard. Maybe I'll come up with a solution tomorrow. Or maybe it'll just look a bit awkward for now. :/
