### ISSUE TITLE
Strange numbering of sections

### ISSUE THREAD

**Issue by r12a** [w3c/tr-design#46]
The very odd numbering of sections shown in section 2 the picture occurs on Firefox, Chrome, Safari and Edge. It's not only the toc – the numbering is the same in the body of the text. Is it anything to do with the style sheet?

![screen shot 2016-01-15 at 07 53 31](https://cloud.githubusercontent.com/assets/4839211/12348401/fbd2ebda-bb5e-11e5-8fc2-fadf5df563a4.png)

**Comment by fantasai** [comment]
What's weird about it?

**Comment by r12a** [comment]
2.3 immediately after 2.1
2.2 immediately after 2.3.5
2.3.4 after 2.2.3
that's not common here in the UK ;-)

**Comment by fantasai** [comment]
lol, okay, that's just me being an idiot. The numbers are all hand-written in this spec, so moving sections messed it up. I'll fix. :)
