### ISSUE TITLE
Figure too large?

### ISSUE THREAD

**Issue by iherman** [w3c/tr-design#47]
I have a figure in my files, with the following markup

```
      <figure id="pwp_figure">
        <img src="figures/pwp.svg" alt="...">
        <figcaption>...</figcaption>
      </figure>
```

with no extra setting for figures. The SVG file does not have explicit width, only a viewport, ie, a pure 'rescaling' figure. The 1st attached screenshot shows that the figure occupies the full width of the page (using latest release of FF on Mac OS). Replacing the svg with png shows that the full width of the png file is used.

I also tried to explicitly set the width of the figure to 50rem. Using inline style I get what is shown on the 2nd screen shot.

(The respec uses the base.css in /2016/01/)
![screen shot 2016-01-20 at 10 43 56](https://cloud.githubusercontent.com/assets/520723/12445300/d710cef8-bf63-11e5-9046-31d4b8f6240c.png)
![screen shot 2016-01-20 at 10 50 03](https://cloud.githubusercontent.com/assets/520723/12445299/d70fa87a-bf63-11e5-93b6-a990ce91784d.png)

**Comment by fantasai** [comment]
Okay, I've got two options here:
  a) Keep images at viewport size by default, help you center the image
  b) Make images max out at 50em by default, authors have to use .overlarge if needed.
I'm thinking b) probably makes the most sense, so gonna do that. Let me know if you think a) is better. :)

**Comment by iherman** [comment]
Your option b is definitely the way to go in my view, too. Thanks

> Okay, I've got two options here:
> a) Keep images at viewport size by default, help you center the image
> b) Make images max out at 50em by default, authors have to use .overlarge if needed.
> I'm thinking b) probably makes the most sense, so gonna do that. Let me know if you think a) is better. :)
