### ISSUE TITLE
On mobile, code font is smaller than text font

### ISSUE THREAD

**Issue by jyasskin** [w3c/tr-design#48]
https://webbluetoothcg.github.io/web-bluetooth/#device-discovery (A bikeshed [spec](https://github.com/WebBluetoothCG/web-bluetooth/blob/gh-pages/index.bs)), when rendered on Android Chrome, looks like:
![Screenshot showing code font text smaller than normal text](https://cloud.githubusercontent.com/assets/83420/12473179/aecff0b6-bfc4-11e5-8daf-2bf96eba3896.png)

Instead, the code font should be approximately the same size as the paragraph text.

**Comment by fantasai** [comment]
You need to have &lt;meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"> in your header. If Bikeshed isn't spitting that out for you, file a bug against Bikeshed?
