### ISSUE TITLE
Please don't uppercase note markers

### ISSUE THREAD

**Issue by jyasskin** [w3c/tr-design#49]
https://webbluetoothcg.github.io/web-bluetooth/#bluetoothgattservice has a note whose header is "BluetoothGATTService attributes", which references a `BluetoothGATTService` type. That's being rendered as "BLUETOOTHGATTSERVICE ATTRIBUTES", which isn't the name of the type.

**Comment by fantasai** [comment]
Added code { text-transform: none; }. Let me know if this solves the problem, or non-code marker text also needs to be left alone.

**Comment by jyasskin** [comment]
That's sufficient, thanks!
