### ISSUE TITLE
Minification and long-caching

### ISSUE THREAD

**Issue by darobin** [w3c/tr-design#5]
It would not be a bad idea to have the entry point sheets just be shells that import other styles. Those other styles are to be minified, given a name based on a hash of the content, and set to have eternal caching.

**Comment by astorije** [comment]
The base file is 60 lines and sheets are in general kept small (at the moment). Do the drawbacks of minifying (keeping in sync, ...) outcome the advantages at that stage?

Maybe minifying will only be interesting in the future, no? I mean, right now the HTML markup size and the CSS files are at very different orders of magnitude.

**Comment by tripu** [comment]
I think modularising CSS as @darobin suggests is a good idea.

I also understand we can benefit from caching, and take measures to improve it (eg, freeze these files, freeze their URLs, send optimistic `Expires` HTTP headers), regardless of whether CSS is minified or not.

I personally don't have strong feelings about minification, but recently I have heard colleagues at W3C express their distaste for minification. To me, those were certainly opinions to consider. I guess there are even more reasons than the usual (I mean especially for W3C) to serve our markup and CSS un-minified&nbsp;&mdash;&nbsp;it should be a showcase of good practices, a reference for web folks, and a template for the curious :¬)

**Comment by darobin** [comment]
@tripu I don't disagree with the sentiment of exemplarity but 1) I don't think anyone is going to learn CSS from looking at ours, it's way too simple, and 2) minification and long-caching are best practices. Part of my motivation here is precisely to make use of them.

@astorije The problem isn't so much the CSS size as the expiration headers. Even a small style sheet is costly if you've got to hit the network to get it.

This is very simple to handle, it's just a few lines of JS to handle it as a build tool. It would also allow us to generate all the status-specific styles instead of maintaining them as they are today, which is a win.

The setup is simple. Minify `base.css` to `deadb33f.min.css` (matching a hash of its content). Have a server rule that sets expiration for all .min.css in the distant future. Generate all status-specific wrappers to refer to the newly generated style sheet. Ship. I've written code like that a bunch of times, I can most likely just paste it from another project.

**Comment by astorije** [comment]
> @astorije The problem isn't so much the CSS size as the expiration headers. Even a small style sheet is costly if you've got to hit the network to get it.

Isn't that solved by caching instead?

Note that my comment was only about minifying, I am also in favor of caching (and to that I add gzipping that wasn't mentioned earlier).

**Comment by darobin** [comment]
Well, if we're going to support good practices I would rather we supported them all rather than a subset :)

**Comment by astorije** [comment]
I am biaised on this, so don't listen to me maybe.
I have never been a fan of minifying (when it solves 1% of the issue and caching+gzipping solve the other 99%) and I definitely don't classify it as a good practice. You know, there are these things that don't enter the good or bad practices categories, but a third one that says "it depends on the situation". That's one of them IMO :-)

**Comment by plehegar** [comment]
To me, this issue is about deployment, and deployment depends on our infrastructure and what our servers are capable of. I'd rather not think about that during the designing phase to be honest. I intentionally removed the server side include magic from our style sheets to facilitate edition and testing in the repo. But that doesn't mean we can't use it for deployment once the styles are approved.

**Comment by astorije** [comment]
:+1:

**Comment by plehegar** [comment]
In https://github.com/w3c/tr-design/blob/gh-pages/README.md , I added the following:
"The W3C webmaster will deploy the new style sheets and associated assets no later than December 1st, if approved by the Director."

This ought to make it clear that the W3C webmaster is in charge of the deployment (and not the designer).

**Comment by fantasai** [comment]
Marking this closed, per plh's comment.
