### ISSUE TITLE
Unofficial style missing in new set of styles

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/tr-design#51]
This is a request to add "w3c-unofficial.css" to the 2016 styles directory. 

ReSpec's logic for selecting between the new and old styles is fairly simple (and would like to keep it so) - so it would be great to not have to special case for unofficial specs (by having to drop out to `../` from the 2016 dir).

**Comment by tripu** [comment]
I don't see why not :+1:

(This will be a perfect first commit for that new &ldquo;2017-development&rdquo; branch&hellip; ;)

**Comment by fantasai** [comment]
Not sure why you're filing this bug. It's already in there.

**Comment by marcoscaceres** [comment]
@fantasai, where? Am I blind? ... maybe it just hasn't been moved into place?
 https://www.w3.org/StyleSheets/TR/2016/

**Comment by marcoscaceres** [comment]
I see in your src dir you have a symlink, but this still gives me a 404:
https://www.w3.org/StyleSheets/TR/2016/w3c-unofficial.css

Having said that, I noticed that w3c-unofficial.css is actually:
https://www.w3.org/StyleSheets/TR/2016/W3C-UD.css

So will just use that.

**Comment by fantasai** [comment]
Heh. Works for me. :)

**Comment by tripu** [comment]
I suggest we get rid of `w3c-unofficial.css` and of the symlink now, and keep only `W3C-UD.css` (the consistent filename), before tools and users start relying on that copy, and it's too late.

WDYT?

**Comment by fantasai** [comment]
Works for me.
