### ISSUE TITLE
addEventListener on MediaQueryList?

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/tr-design#54]
In fixup.js, I noticed: 

``` JS
  var sidebarMedia = window.matchMedia('screen and (min-width: 78em)');
  if (sidebarMedia.addEventListener) {
   ...
  } else if (sidebarMedia.addListener) {
   ...
  }
```

According to caniuse.com, matchMedia() only became available in IE10, which probably means that `sidebarMedia.addListener` will never run (because IE was supporting addEventListener() properly by then). Maybe that second if statement could be removed?

**Comment by marcoscaceres** [comment]
Oops, I forgot that matchMedia()'s returns an object with addListener; it's not IE related.

**Comment by marcoscaceres** [comment]
Inverse question holds tho? What UA is using "addEventListener" on MediaQueryList?

**Comment by fantasai** [comment]
Chrome was running that code path. But they seem to support the standard one, so deleted.
