### ISSUE TITLE
top navigation arrow misplaced?

### ISSUE THREAD

**Issue by plehegar** [w3c/tr-design#56]
http://w3c.github.io/hr-time/
does have the top navigation arrow appearing before the spec title, instead of the bottom left corner. CSS issue?

**Comment by fantasai** [comment]
ReSpec is inlining the styles on the EDs, and it needs to be updated to the latest changes from this week.

**Comment by tripu** [comment]
@plehegar, iiuc, that might be related to an issue I detected on our site (older CSS stuck in our Varnish cache), which @deniak fixed later.
