### ISSUE TITLE
Propdef tables no longer have a width limit on their TH elements

### ISSUE THREAD

**Issue by tabatkins** [w3c/tr-design#60]
The stylesheet no longer has any special handling for `<th>` elements in propdef tables, which means that they look really dumb now with both columns being 50% wide and the th being centered.

Looking back at CSSWG's default.css, it looks like the necessary rule was, for some bizarre reason, nestled right in the middle of the .proptable styles, which were rightfully deleted.

We just need this back:

```
    .propdef th {
        font-style: italic;
        font-weight: normal;
        text-align: left;
        width: 3em;
    }
```

Since this actually is needed by all the `*def` types, I guess this is actually a generic `table.def th` rule that needs to be restored.

**Comment by fantasai** [comment]
Fixed. Will need to beg the webmaster to update now. :)

**Comment by tripu** [comment]
Personally, I don't like that we're still making changes, and that [we have no branches, in practice](https://github.com/w3c/tr-design/network).
However small these changes are, we are not giving participants in the project enough time to test (or even to _notice_).
I'd stick to [rc2](https://github.com/w3c/tr-design/releases/tag/v1.0.0-rc2) for deployment next Tuesday.

But I defer to @plehegar (boss) and to @deniak (webmaster) :)

**Comment by tabatkins** [comment]
I understand in general, but this is a bugfix of an accidental reversion. You'd hear _howling_ if this wasn't fixed in the live stylesheets, believe me. ^_^
