### ISSUE TITLE
Logo is white on transparent

### ISSUE THREAD

**Issue by tabatkins** [w3c/tr-design#67]
Is it intentional that linking directly to the logo is worthless, and it must always be accompanied by a background-color?

If so, the recommended background-color should be in the required instructions, but I highly suspect that this is unintentional and we're just working around it heavily right now.

**Comment by tabatkins** [comment]
It's probably intended to be against `#1a5e9a`, since there's a background `<rect>` in the SVG with that color which is set to 0 opacity.

**Comment by fantasai** [comment]
This is intentional, because it's to get the hover effect. It's not listed in the instructions because the instructions also say to import the TR stylesheet, which already takes care of this for you!
