### ISSUE TITLE
ul.index users vendor prefixes

### ISSUE THREAD

**Issue by plehegar** [w3c/tr-design#69]
We ought to avoid using vendor prefix in the W3C official base style sheet.

**Comment by plehegar** [comment]
I removed those from the 2016 branch https://github.com/w3c/tr-design/commit/69b0233a0f934f943c2350afacb0e9633e15787c

but I'd welcome alternative suggestions.

**Comment by tabatkins** [comment]
Uh, why should we not include them?  The unprefixed version is there, and including prefixes improves compatability.  Unless you have usage data showing that they should be unnecessary in practice, I don't think being dogmatic about prefixes is useful.

**Comment by fantasai** [comment]
It's the W3C website... I think it's one of the few places where it's okay to be dogmatic about prefixes. It's a minor enhancement to use the columns, so I think it's okay to remove the prefixed versions. Hopefully everyone upgrades to the standard syntax soon and it's no longer a problem...
