### ISSUE TITLE
The `.head > :first-child` rule breaks things

### ISSUE THREAD

**Issue by tabatkins** [w3c/tr-design#71]
I'm not sure what it was intended to do, but in https://github.com/w3c/tr-design/commit/02507888b7be04710d5f9e95372f86007c78207d Lea added a rule `.head > :first-child { float: right; margin: 0; }`.

I _presume_ this was supposed to target the logo image, but that doesn't work if specs aren't using the _precise_ head markup that it's anticipating.  In particular, the UI Events group is using boilerplate that wraps the logo and headings in a `<header>` element, so _that's_ what gets caught by the rule, and it messes things up.

This should be using a `.head .logo` selector.  Nothing in the stylesheet should be assuming code structure that isn't strictly required.

**Comment by fantasai** [comment]
So I was _trying_ not to make too many changes to pubrules, and therefore didn't require a .logo class on the logo. (Apparently that's just a thing we do. Not all groups do that. T_T) So had to switch the selector there. Tried a different route, let me know if that solves it...

**Comment by tabatkins** [comment]
That looks _exceedingly_ likely to break things too.  I'm not willing to put that into Bikeshed's default stylesheet.

If a spec doesn't use `.logo`, it just won't get floated.  Don't think that's a huge deal.  Both Bikeshed and ReSpec apply `.logo` as part of their boilerplate, so the only thing it'll possibly skip is a spec using some custom preprocessor that for some reason chose not to match the de-facto markup of every other spec.

**Comment by fantasai** [comment]
Which we have enough of that I've run into this problem, or else I wouldn't have changed it from .logo, now would I.

**Comment by tabatkins** [comment]
Right. But as I said last night in IRC, the logo not floating is a much smaller problem than something random in the header floating unexpectedly.  It's impossible to target the logo "generically" in a way that isn't very likely to hit some perfectly innocuous markup and totally wreck it - I've already shown how `.head > :first-child` breaks, and `.head p:not(.copyright)` has an obvious failure mode as well.

My fundamental confusion here is why you're implicitly claiming you _can_ require certain non-obvious markup patterns in the head (logo must be first child, logo must be the only non-copyright p element), but _can't_ require a `.logo` class.  They seem roughly equivalent to me, but the latter is actually _safe_ to target with `float: right`.

**Comment by fantasai** [comment]
As I said, I'm happy to require .logo for 2017, but since pubrules hasn't been updated to require it, I'm not going to do that for 2016. Bikeshed can import the 2017 styles, which we can fork off once things settle down a bit.
