### ISSUE TITLE
Flakey sidebar controls 

### ISSUE THREAD

**Issue by sandhawke** [w3c/tr-design#74]
The sidebar controls don't work right for me.

I'm using https://www.w3.org/TR/2016/WD-webmention-20160301/

at startup there are two arrows in the lower left
when I mouse over them, two"collapse sidebars" show up.    Clicking on the upper one does nothing.  Clicking on the lower one works.

I'm on Ubuntu 15.10 (64-bit).  Same behavior in both Chromium 48.0.2564.82 and FF 44.0.2

**Comment by sandhawke** [comment]
![without-mouse-over](https://cloud.githubusercontent.com/assets/110902/13442331/b194c7ca-dfc9-11e5-97e5-e477bdf6657a.png)

**Comment by iherman** [comment]
I also get into problems on an iPad. The page comes with three arrows, but I end up soon in a state with the tic deployed, two full buttons for collapse, but none of the work (see image below)

> The sidebar controls don't work right for me.
> 
> I'm using https://www.w3.org/TR/2016/WD-webmention-20160301/
> 
> at startup there are two arrows in the lower left
> when I mouse over them, two"collapse sidebars" show up. Clicking on the upper one does nothing. Clicking on the lower one works.
> 
> I'm on Ubuntu 15.10 (64-bit). Same behavior in both Chromium 48.0.2564.82 and FF 44.0.2

**Comment by fantasai** [comment]
The spec contains the following code: `<body class="h-entry toc-sidebar" role="document" id="respecDocument"><p id="toc-nav"><a id="toc-jump" href="#toc"><span aria-hidden="true">↑</span> <span>Jump to Table of Contents</span></a><a id="toc-toggle" href="#toc"><span aria-hidden="true">←</span> <span>Collapse Sidebar</span></a></p>`

Which should just be `<body class="h-entry" role="document" id="respecDocument">`

Guessing this has something to do with respec dumping the state of the DOM to static HTML... The sidebar setting (`class="toc-sidebar"`) and the JS-generated controls (`<p id="toc-nav">`) should not be part of the output.

**Comment by deniak** [comment]
I removed the wrong markup but indeed, that's probably something respec is adding.

**Comment by iherman** [comment]
It indeed works on the iPad now.

There is still an oddity, though. When loading the document, what I get are the up and right arrows only. If I interact with this stuff (eg, I pop out the sidebar and then collapse it again) what I get is the arrow _plus_ the text (eg, "Pop out Sidebar") until I click somewhere on the text. I would think that the hover does not work, and the text remains there (which is quite disturbing because the hover text characters are actually way larger than the body text, which may be an issue by itself).

This may be a bug on the IOS Safari engine but I am not sure: how should a browser react on hover on a tablet?

**Comment by plehegar** [comment]
it's a respec/fixup interaction issue. Either we modify respec to ignore fixup.js when dumping the DOM, or we modify fixup.js to be a null-op if the changes from it were already applied.

**Comment by plehegar** [comment]
btw, this explains why the spec-generator excludes all official scripts:
 https://github.com/w3c/spec-generator/blob/master/generators/respec.js#L29

**Comment by plehegar** [comment]
the more I think about this and the more I think that fixup.js should ensure that it's not applied twice, since we don't require drafts to not contain the changes from fixup.

**Comment by plehegar** [comment]
It takes this back. respec inserts the fixup scrupt twice in the document. so we need to fix respec, not tr-design.

**Comment by plehegar** [comment]
Fixed in respec by @marcoscaceres .
