### ISSUE TITLE
Strange positioning in the header part...

### ISSUE THREAD

**Issue by iherman** [w3c/tr-design#75]
I do not know whether this is a CSS or respec issue. However, look at the image below: there is a huge extra space for the reference to the errata and the alternative format...

![screen shot 2016-03-02 at 10 50 08](https://cloud.githubusercontent.com/assets/520723/13456700/bd923120-e064-11e5-9507-dc8cb1e243e5.png)

**Comment by tripu** [comment]
@fantasai, I think the culprit is [this rule](https://github.com/w3c/tr-design/blob/gh-pages/src/base.css#L117).
What shall we do with paragraphs inside `.head` that are _not_ the copyright notice (and contain links)?

**Comment by fantasai** [comment]
Yeah, this is fallout from not requiring class="logo" on the logo... Could try to fix by changing the selector to p:not(.copyright):first-child
