### ISSUE TITLE
Printing with the new styles

### ISSUE THREAD

**Issue by halindrome** [w3c/tr-design#76]
I noticed today that the link from the bottom of the document to the table of contents shows up when you print a document.  That should be suppressed in the printer stylesheet.

**Comment by fantasai** [comment]
There shouldn't be one, I think. Earlier versions of the style depended on an  id="back-to-top", but we dropped that in favor of generating it in JS at the top of the page.

Can you point me at a spec that's problematic?

**Comment by fantasai** [comment]
Closing this bug, since it shouldn't occur on a properly-generated page.
