### ISSUE TITLE
min-width on table headings causes issues

### ISSUE THREAD

**Issue by ZoeBijl** [w3c/tr-design#78]
There seems to be a minimum width set on table headings; this quickly causes problems if you have more than two columns:

![Table grows beyond document width due to minimum width on table headings as shown by the web inspector in Chrome](https://cloud.githubusercontent.com/assets/5457769/13697990/241680ee-e769-11e5-94f3-95985e0605f6.png)

Was this tested with different tables? Is this an issue with this specific document (aria-practices)?

**Comment by fantasai** [comment]
This rule is coming from the aria-apg.css stylesheet. File a bug against whoever is maintaining that.

**Comment by ZoeBijl** [comment]
Crap, my bad. It's really obvious too, I'm an idiot…
