### ISSUE TITLE
fixup.js does not look for the buttons it adds so can add them twice

### ISSUE THREAD

**Issue by halindrome** [w3c/tr-design#79]
In ReSpec there is an option to save a snapshot.  Such a snapshot will have the ToC toggle buttons already in it.  Then, when fixup.js loads when you bring up the snapshot, it will add them again!

We need to 1) not add them if they are already in the document, and 2) have a hook in fixup.js to remove them so save snapshot or others can rip them out if needed.

**Comment by fantasai** [comment]
Okay, should be fixed. Let me know if not.
