### ISSUE TITLE
Table columns are too narrow

### ISSUE THREAD

**Issue by halindrome** [w3c/tr-design#85]
This was originally in  https://github.com/w3c/respec/issues/666 from @rtoy

In the latest release, the parameter description column is very narrow which makes it difficult to read. See, for example, http://webaudio.github.io/web-audio-api/#methods-6. The description of the when parameter is smashed into a narrow column that makes for hard reading.

Is there a way to make the columns a bit wider?

**Comment by fantasai** [comment]
What makes you think this is a tr-design problem? This table isn't even using class="data".

**Comment by halindrome** [comment]
The problem is that the new styles limit the width of the total page.
Consequently the table columns are artificially restricted.

**Comment by marcoscaceres** [comment]
> On 19 Mar 2016, at 3:13 PM, Shane McCarron notifications@github.com wrote:
> 
> The problem is that the new styles limit the width of the total page.

Fwiw, would be nice to be able to opt out of the restricted width. I use a 40" 4K screen at work and the restricted width does not much for me (I'm also capable of resizing the browser window all on my own... Like a big kid👶). 

> Consequently the table columns are artificially restricted.

**Comment by fantasai** [comment]
halindrome: http://fantasai.inkedblade.net/style/design/w3c-restyle/2016/sample#table-tailoring

marcos: Well, you can be a big kid and use a user style sheet then. :) 50em is already longer than the recommended limits for line lengths.

Other notes on the Web Audio spec: It should not put code in a `<blockquote>` unless it's actually quoting someone, and the webIDL blocks should be using .def styling for consistency with other specs that have entity definition blocks.
