### ISSUE TITLE
Logo image should be self-contained, not rely on further CSS for styling

### ISSUE THREAD

**Issue by tabatkins** [w3c/tr-design#88]
The current logo image is a bare square with the "W3C" text butting right up against the edge.  To fix this, the stylesheet adds a thick border and a border-radius, to give the text some breathing room and make it nice and rounded.

This should instead just be baked into the logo image itself.  It's kinda silly for the logo image to be too ugly to be displayed directly.

(This causes problems with Bikeshedded specs, as they'll get a W3C-colored thick border around their logos regardless of what logo they actually use.)

**Comment by fantasai** [comment]
Forgot to mark this fixed...
