### ISSUE TITLE
TOC roll-over text shimmers/jumps...

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/tr-design#89]
In Firefox, the side bar text shimmers/jumps as the user rolls over the TOC... Note: this is [probably a bug in Gecko](https://bugzilla.mozilla.org/show_bug.cgi?id=1258617), but we might be able to fix it by doing something in the CSS. 

Steps:
1. make browser window nice and big.  
2. load the following, wait for the side-bar to show up: https://w3c.github.io/manifest/
3. roll over the side-bar table of contents on the left

Expected:
 Smooth roll over (see other browsers)

Actual:
  The text seems to jump a few pixels as one rolls over.

**Comment by fantasai** [comment]
Are you still seeing this? I'm not still seeing this...

**Comment by marcoscaceres** [comment]
@fantasai, it seems to only happen on 4K display. I think it's a bug in Gecko, so closing.
