### ISSUE TITLE
"data" table is shifted to the right

### ISSUE THREAD

**Issue by iherman** [w3c/tr-design#93]
When the window is relatively large, a data table gets a large left indent, not in sync with the rest of the text. See the screen dump below; the table itself has a thead with th-s, and no th-s in the body.

![screen shot 2016-04-01 at 14 53 26](https://cloud.githubusercontent.com/assets/520723/14207314/96273690-f819-11e5-8ede-d98324a230d2.png)

**Comment by iherman** [comment]
Is this issue is the same as #104? (I believe it is...)

**Comment by tripu** [comment]
It seems so.
