### ISSUE TITLE
WG-Note CSS doesn't link

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/tr-design#96]
Getting different result for https://www.w3.org/StyleSheets/TR/2016/W3C-Note (sometimes 200Ok and sometimes a 300). 

Please see https://github.com/w3c/respec/pull/699

**Comment by fantasai** [comment]
Link to https://www.w3.org/StyleSheets/TR/2016/W3C-NOTE ?

**Comment by marcoscaceres** [comment]
Why did you close this? It's still busted. To reproduce click the link multiple times

**Comment by marcoscaceres** [comment]
I got the 300 again after clicking the link twice.
