### ISSUE TITLE
"2.1.3 Switch Statements" links to "Index Tables"

### ISSUE THREAD

**Issue by jyasskin** [w3c/tr-design#97]
Try clicking on 2.1.3 in the ToC of https://w3c.github.io/tr-design/src/sample.html.

**Comment by tripu** [comment]
@jyasskin, as that is just a sample document with fictitious content that @fantasai kindly put together, I think we are not worried about that kind of errors.

**Comment by tripu** [comment]
(Thank you for reporting, though!)
